import type { BetaState, BetaTaskPriority } from "@/domain/beta";
import { analyzeWeakPoints } from "@/domain/analytics/weak-points";
import { buildCurriculumCatalog } from "@/domain/learning/curriculum";
import { resolveContinueLearning } from "@/domain/learning/learning-experience";

export interface PlanSuggestion { id:string;title:string;subjectId?:string;chapterId?:string;knowledgePointId?:string;curriculumId?:string;sectionId?:string;type:"learning"|"review"|"practice"|"recitation"|"reading";minutes:number;priority:BetaTaskPriority;reason:string;source:"overdue_task"|"review"|"weak_point"|"recitation"|"vocabulary"|"goal"|"neglected"|"curriculum"; }
export interface SmartPlan { date:string;availableMinutes:number;totalMinutes:number;suggestions:PlanSuggestion[];dataSufficient:boolean; }
export function buildSmartPlan(state:BetaState,date:string):SmartPlan{
  const profileDay=state.planningProfile?.days.find((d)=>d.date===date);const available=profileDay?.availableMinutes??state.planningProfile?.dailyMinutes??120;const weak=analyzeWeakPoints(state,date);const candidates:PlanSuggestion[]=[];
  for(const task of state.tasks.filter((t)=>t.status!=="completed"&&t.date<=date).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,4))candidates.push({id:`task:${task.id}`,title:task.title,subjectId:task.subjectId,chapterId:task.chapterId,type:"learning",minutes:task.plannedMinutes,priority:task.date<date?"high":task.priority,reason:task.date<date?"逾期任务需要重新安排":"已安排任务",source:"overdue_task"});
  for(const review of state.reviewItems.filter((r)=>r.status==="due"&&r.dueDate<=date).sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5))candidates.push({id:`review:${review.id}`,title:review.title,subjectId:review.subjectId,chapterId:review.chapterId,type:review.kind==="question"?"practice":review.kind==="recitation"?"recitation":"review",minutes:review.kind==="question"?20:15,priority:review.dueDate<date?"high":"medium",reason:review.dueDate<date?"复习已逾期":"今日到期复习",source:"review"});
  const queuedTargets=new Set(state.reviewItems.filter((item)=>item.status==="due").map((item)=>item.targetId));
  for(const item of state.recitations.filter((entry)=>entry.status!=="mastered"&&(!entry.nextReviewAt||entry.nextReviewAt<=date)&&!queuedTargets.has(entry.id)).slice(0,3))candidates.push({id:`recitation:${item.id}`,title:item.title,subjectId:item.subjectId,chapterId:item.chapterId,knowledgePointId:item.knowledgePointId,type:"recitation",minutes:15,priority:item.nextReviewAt&&item.nextReviewAt<date?"high":"medium",reason:item.nextReviewAt&&item.nextReviewAt<date?"背诵复习已逾期":"背诵内容今日到期",source:"recitation"});
  const englishId=state.subjects.find((item)=>item.slug==="english")?.id;
  for(const word of state.vocabulary.filter((item)=>item.familiarity!=="mastered"&&!!item.nextReviewAt&&item.nextReviewAt<=date&&!queuedTargets.has(item.id)).slice(0,5))candidates.push({id:`vocabulary:${word.id}`,title:`复习单词 ${word.word}`,subjectId:englishId,type:"review",minutes:5,priority:word.nextReviewAt!<date?"high":"medium",reason:word.nextReviewAt!<date?"单词复习已逾期":"单词今日到期",source:"vocabulary"});
  for(const item of weak.weakKnowledgePoints.slice(0,3))if(!candidates.some((c)=>c.knowledgePointId===item.knowledgePointId))candidates.push({id:`weak:${item.knowledgePointId}`,title:`复习 ${item.title}`,subjectId:item.subjectId,chapterId:item.chapterId,knowledgePointId:item.knowledgePointId,type:"practice",minutes:25,priority:item.confidence==="high"?"high":"medium",reason:`${item.reason.join("；")}（${item.confidence} confidence）`,source:"weak_point"});
  const lesson=resolveContinueLearning(state,buildCurriculumCatalog(state));if(lesson)candidates.push({id:`curriculum:${lesson.section.id}`,title:`继续学习：${lesson.chapter.title} · ${lesson.section.title.replace(/^\d+\.\d+\s*/,"")}`,subjectId:lesson.curriculum.subjectId,chapterId:lesson.chapter.sourceChapterId,curriculumId:lesson.curriculum.id,sectionId:lesson.section.id,type:"learning",minutes:lesson.section.estimatedMinutes,priority:"medium",reason:"按课程顺序进入下一节未完成内容",source:"curriculum"});
  const lastBySubject=new Map<string,string>();for(const session of state.studySessions.filter((s)=>s.completed&&s.subjectId))if((lastBySubject.get(session.subjectId!)??"")<session.endedAt)lastBySubject.set(session.subjectId!,session.endedAt);const priority=state.planningProfile?.subjectPriorities??{};const neglected=state.subjects.filter((s)=>!s.id.startsWith("subject-universal-")).sort((a,b)=>(priority[b.id]??0)-(priority[a.id]??0)||(lastBySubject.get(a.id)??"").localeCompare(lastBySubject.get(b.id)??""))[0];if(neglected)candidates.push({id:`neglected:${neglected.id}`,title:`继续学习${neglected.name}`,subjectId:neglected.id,type:"learning",minutes:30,priority:"medium",reason:lastBySubject.has(neglected.id)?"近期学习频率较低":"尚无学习记录",source:"neglected"});
  const suggestions:PlanSuggestion[]=[];let total=0;for(const item of candidates){if(total>=available)break;const minutes=Math.max(5,Math.min(item.minutes,available-total));suggestions.push({...item,minutes});total+=minutes;}return{date,availableMinutes:available,totalMinutes:total,suggestions,dataSufficient:state.studySessions.length>0||state.tasks.length>0||state.reviewItems.length>0||state.recitations.length>0||state.vocabulary.length>0||weak.weakKnowledgePoints.length>0};
}
