import type { BetaState } from "@/domain/beta";

export interface WeakEvidence { incorrectAttempts:number; totalAttempts:number; activeMistake:boolean; overdueReviews:number; difficultReviews:number; recitationLapses:number; mastery:string; }
export interface WeakPointResult { knowledgePointId:string; subjectId:string; chapterId:string; title:string; score:number; confidence:"low"|"medium"|"high"; evidenceCount:number; reason:string[]; evidence:WeakEvidence; }
export interface WeakAnalytics { weakKnowledgePoints:WeakPointResult[]; weakSubjects:{subjectId:string;score:number;evidenceCount:number}[]; weakChapters:{chapterId:string;subjectId:string;score:number;evidenceCount:number}[]; }

export function analyzeWeakPoints(state:BetaState,today:string):WeakAnalytics{
  const results:WeakPointResult[]=[];
  for(const point of state.knowledgePoints){const questions=state.questions.filter((q)=>q.knowledgePointId===point.id);const ids=new Set(questions.map((q)=>q.id));const attempts=state.questionAttempts.filter((a)=>ids.has(a.questionId));const incorrect=attempts.filter((a)=>!a.correct).length;const activeMistake=state.wrongQuestions.some((w)=>ids.has(w.questionId)&&!w.mastered);const pointReviews=state.reviewItems.filter((r)=>r.targetId===point.id);const overdue=pointReviews.filter((r)=>r.status==="due"&&r.dueDate<today).length;const difficultReviews=pointReviews.filter((r)=>(r.difficulty??5)>5.5||(r.ease??2.3)<1.9).length;const recitation=state.recitations.find((r)=>r.knowledgePointId===point.id);const recitationReview=recitation?state.reviewItems.find((r)=>r.kind==="recitation"&&r.targetId===recitation.id):undefined;const lapses=recitationReview?Math.max(0,Math.round((recitationReview.difficulty??5)-5)):0;const score=incorrect*3+(activeMistake?4:0)+overdue*2+difficultReviews*2+lapses*2+(point.mastery==="reviewing"?2:point.mastery==="learning"?1:0);const evidenceCount=attempts.length+(activeMistake?1:0)+pointReviews.length+(recitationReview?.reviewCount??0)+(point.mastery!=="new"?1:0);if(score<=0||evidenceCount===0)continue;const reason:string[]=[];if(incorrect)reason.push(`${incorrect}/${attempts.length} incorrect attempts`);if(activeMistake)reason.push("active mistake");if(overdue)reason.push(`${overdue} overdue reviews`);if(difficultReviews)reason.push(`${difficultReviews} difficult reviews`);if(lapses)reason.push(`${lapses} recall lapses`);if(point.mastery==="reviewing"||point.mastery==="learning")reason.push(`mastery: ${point.mastery}`);results.push({knowledgePointId:point.id,subjectId:point.subjectId,chapterId:point.chapterId,title:point.title,score,confidence:evidenceCount>=6?"high":evidenceCount>=3?"medium":"low",evidenceCount,reason,evidence:{incorrectAttempts:incorrect,totalAttempts:attempts.length,activeMistake,overdueReviews:overdue,difficultReviews,recitationLapses:lapses,mastery:point.mastery}});}
  results.sort((a,b)=>b.score-a.score||b.evidenceCount-a.evidenceCount);
  const aggregate=(key:"subjectId"|"chapterId")=>{const map=new Map<string,{score:number;evidenceCount:number;subjectId:string}>();for(const item of results){const id=item[key];const prior=map.get(id)??{score:0,evidenceCount:0,subjectId:item.subjectId};prior.score+=item.score;prior.evidenceCount+=item.evidenceCount;map.set(id,prior);}return[...map].map(([id,value])=>({[key]:id,...value})).sort((a,b)=>b.score-a.score);};
  return{weakKnowledgePoints:results,weakSubjects:aggregate("subjectId") as WeakAnalytics["weakSubjects"],weakChapters:aggregate("chapterId") as WeakAnalytics["weakChapters"]};
}

