"use client";

import { useState, type FormEvent } from "react";
import { Badge, Button, Card } from "@/components/ui";
import type { BetaChapter, BetaKnowledgePoint } from "@/domain/beta";
import type { Locale } from "@/i18n/config";
import { useBetaData } from "@/providers";
import { areaClass, EmptyState, Field, fieldClass, localDate, Modal, nowEntity, Tabs, uid } from "./shared";
import { addKnowledgeToRecitation } from "./recitation-service";
import { QuestionEngine } from "./question-engine";
import { PdfLibrary } from "./pdf-library";

const copy = {
  "zh-CN": { core: "核心内容", structure: "知识结构", high: "高频考点", choice: "选择题", subjective: "简答 / 论述", notes: "我的笔记", pdf: "PDF 资料", noContent: "此目录尚无学习正文。可导入自己的资料、创建笔记或添加知识点。", addPoint: "添加知识点", concept: "核心概念", key: "重点", pitfall: "易错点", highLabel: "我标记的高频", frequency: "重点标记", ordinary: "普通", highValue: "高频", addRecite: "加入背诵", addReview: "加入复习", addQuestion: "添加主观题", prompt: "题目", thinking: "答题思路", keywords: "核心关键词（逗号分隔）", reference: "参考要点", answer: "我的答案 / 笔记", short: "简答", essay: "论述", source: "来源", save: "保存", noHigh: "还没有标记高频考点。", noQuestions: "此章节暂无主观题。请添加自己有权使用的题目。", noNotes: "还没有关联笔记。", addNote: "新建章节笔记", noOfficial: "高频标记由你维护，不代表官方统计或真题频率。" },
  en: { core: "Core content", structure: "Knowledge structure", high: "Key topics", choice: "Choice questions", subjective: "Short / essay", notes: "My notes", pdf: "PDF materials", noContent: "No study text is saved for this outline yet. Import your material, create a note, or add a point.", addPoint: "Add knowledge point", concept: "Core concept", key: "Key points", pitfall: "Pitfalls", highLabel: "My key topics", frequency: "Priority mark", ordinary: "Standard", highValue: "High", addRecite: "Add to recitation", addReview: "Add to review", addQuestion: "Add subjective question", prompt: "Question", thinking: "Approach", keywords: "Keywords (comma-separated)", reference: "Reference points", answer: "My answer / notes", short: "Short answer", essay: "Essay", source: "Source", save: "Save", noHigh: "No topics marked as key yet.", noQuestions: "No subjective questions for this chapter. Add material you may use.", noNotes: "No linked notes yet.", addNote: "Create chapter note", noOfficial: "Key marks are maintained by you, not official frequency data." },
};

export function ChapterWorkspace({ locale, chapter, onOpenPoint }: { locale: Locale; chapter: BetaChapter; onOpenPoint: (id: string) => void }) {
  const l = copy[locale]; const { state, mutate } = useBetaData(); const [tab, setTab] = useState("core"); const [modal, setModal] = useState<"point" | "question" | "note" | null>(null);
  const units = state.units.filter((item) => item.chapterId === chapter.id).sort((a, b) => a.order - b.order);
  const points = state.knowledgePoints.filter((item) => item.chapterId === chapter.id);
  const questions = state.subjectiveQuestions.filter((item) => item.chapterId === chapter.id);
  const notes = state.notes.filter((item) => item.linkedType === "chapter" && item.linkedId === chapter.id);
  const tabs = (["core", "structure", "high", "choice", "subjective", "notes", "pdf"] as const).map((id) => ({ id, label: l[id] }));
  function addReview(point: BetaKnowledgePoint) {
    mutate((draft) => { if (!draft.reviewItems.some((item) => item.kind === "knowledge" && item.targetId === point.id && item.status === "due")) draft.reviewItems.push({ ...nowEntity(uid("review"), draft.ownerId), kind: "knowledge", targetId: point.id, title: point.title, dueDate: localDate(), status: "due" }); });
  }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!modal) return; const form = new FormData(event.currentTarget); const title = String(form.get("title") ?? "").trim(); if (!title) return;
    mutate((draft) => {
      if (modal === "point") draft.knowledgePoints.push({ ...nowEntity(uid("point"), draft.ownerId), subjectId: chapter.subjectId, chapterId: chapter.id,
        unitId: String(form.get("unit") ?? "") || undefined, title, titleEn: title, coreConcept: String(form.get("content") ?? ""), keyPoints: String(form.get("key") ?? ""), pitfalls: String(form.get("pitfall") ?? ""), personalNote: "", mastery: "new", frequency: "standard", favorite: false });
      if (modal === "question") draft.subjectiveQuestions.push({ ...nowEntity(uid("subjective"), draft.ownerId), subjectId: chapter.subjectId, chapterId: chapter.id,
        kind: String(form.get("kind")) as "short" | "essay", prompt: title, thinking: String(form.get("thinking") ?? ""), keywords: String(form.get("keywords") ?? "").split(",").map((item) => item.trim()).filter(Boolean), referencePoints: String(form.get("reference") ?? ""), ownAnswer: "", source: String(form.get("source") ?? "") });
      if (modal === "note") draft.notes.push({ ...nowEntity(uid("note"), draft.ownerId), title, content: String(form.get("content") ?? ""), tags: [], subjectId: chapter.subjectId, linkedType: "chapter", linkedId: chapter.id, favorite: false });
    }); setModal(null);
  }
  return <section className="grid gap-5"><div><h2 className="type-h2 text-primary">{locale === "en" ? chapter.titleEn : chapter.title}</h2><p className="type-small mt-1 text-muted">{locale === "en" ? "Chapter workspace" : "章节学习工作区"}</p></div><Tabs label={locale === "en" ? chapter.titleEn : chapter.title} value={tab} onChange={setTab} items={tabs} />
    {tab === "core" || tab === "structure" ? <div className="grid gap-3">{units.map((unit) => <Card key={unit.id} padding="sm"><h3 className="type-h3 text-primary">{locale === "en" ? unit.titleEn : unit.title}</h3><div className="mt-3 flex flex-wrap gap-2">{points.filter((point) => point.unitId === unit.id).map((point) => <span key={point.id} className="flex flex-wrap gap-1"><Button size="sm" variant="secondary" onClick={() => onOpenPoint(point.id)}>{locale === "en" ? point.titleEn : point.title}</Button><Button size="sm" variant="ghost" onClick={() => mutate((draft) => addKnowledgeToRecitation(draft, point.id))}>{l.addRecite}</Button><Button size="sm" variant="ghost" onClick={() => addReview(point)}>{l.addReview}</Button></span>)}</div></Card>)}{points.filter((point) => !point.unitId).map((point) => <Card key={point.id} padding="sm"><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => onOpenPoint(point.id)}>{locale === "en" ? point.titleEn : point.title}</Button><Button size="sm" variant="ghost" onClick={() => mutate((draft) => addKnowledgeToRecitation(draft, point.id))}>{l.addRecite}</Button><Button size="sm" variant="ghost" onClick={() => addReview(point)}>{l.addReview}</Button></div></Card>)}{!points.length ? <EmptyState>{l.noContent}</EmptyState> : null}<Button variant="secondary" onClick={() => setModal("point")}>{l.addPoint}</Button></div> : null}
    {tab === "high" ? <div className="grid gap-3"><p className="type-caption text-muted">{l.noOfficial}</p>{points.length ? points.map((point) => <Card key={point.id} padding="sm"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2">{point.frequency === "high" ? <Badge variant="warm">{l.highLabel}</Badge> : null}<Button variant="ghost" onClick={() => onOpenPoint(point.id)}>{locale === "en" ? point.titleEn : point.title}</Button></div><Button size="sm" variant="secondary" onClick={() => mutate((draft) => { const record = draft.knowledgePoints.find((entry) => entry.id === point.id); if (record) record.frequency = record.frequency === "high" ? "standard" : "high"; })}>{point.frequency === "high" ? l.ordinary : l.highValue}</Button></div><p className="type-small mt-2 text-secondary">{point.keyPoints}</p></Card>) : <EmptyState>{l.noHigh}</EmptyState>}</div> : null}
    {tab === "choice" ? <QuestionEngine key={chapter.id} locale={locale} subjectId={chapter.subjectId} initialChapterId={chapter.id} /> : null}
    {tab === "subjective" ? <div className="grid gap-3">{questions.length ? questions.map((question) => <Card key={question.id} padding="sm"><Badge variant="neutral">{question.kind === "short" ? l.short : l.essay}</Badge><h3 className="type-h3 mt-2 text-primary">{question.prompt}</h3><p className="type-small mt-3 text-secondary">{l.thinking}: {question.thinking}</p><p className="type-small mt-1 text-secondary">{l.keywords}: {question.keywords.join(", ")}</p><p className="type-small mt-1 text-secondary">{l.reference}: {question.referencePoints}</p><Field label={l.answer} className="mt-3"><textarea className={areaClass} defaultValue={question.ownAnswer} onBlur={(event) => mutate((draft) => { const record = draft.subjectiveQuestions.find((entry) => entry.id === question.id); if (record) { record.ownAnswer = event.target.value; record.updatedAt = new Date().toISOString(); } })} /></Field></Card>) : <EmptyState>{l.noQuestions}</EmptyState>}<Button variant="secondary" onClick={() => setModal("question")}>{l.addQuestion}</Button></div> : null}
    {tab === "notes" ? <div className="grid gap-3">{notes.length ? notes.map((note) => <Card key={note.id} padding="sm"><h3 className="type-h3 text-primary">{note.title}</h3><textarea aria-label={l.notes} className={`${areaClass} mt-3`} defaultValue={note.content} onBlur={(event) => mutate((draft) => { const record = draft.notes.find((entry) => entry.id === note.id); if (record) record.content = event.target.value; })} /></Card>) : <EmptyState>{l.noNotes}</EmptyState>}<Button variant="secondary" onClick={() => setModal("note")}>{l.addNote}</Button></div> : null}
    {tab === "pdf" ? <PdfLibrary locale={locale} ownerType="subject" ownerRecordId={chapter.id} subjectId={chapter.subjectId} chapterId={chapter.id} /> : null}
    {modal ? <Modal title={modal === "point" ? l.addPoint : modal === "question" ? l.addQuestion : l.addNote} closeLabel={locale === "en" ? "Close" : "关闭"} onClose={() => setModal(null)}><form onSubmit={submit} className="grid gap-4"><Field label={modal === "question" ? l.prompt : locale === "en" ? "Title" : "标题"}><input autoFocus required name="title" className={fieldClass} /></Field>{modal === "point" ? <><Field label={locale === "en" ? "Outline section" : "目录小节"}><select name="unit" className={fieldClass}><option value="">—</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{locale === "en" ? unit.titleEn : unit.title}</option>)}</select></Field><Field label={l.concept}><textarea name="content" className={areaClass} /></Field><Field label={l.key}><textarea name="key" className={areaClass} /></Field><Field label={l.pitfall}><textarea name="pitfall" className={areaClass} /></Field></> : null}{modal === "question" ? <><Field label={locale === "en" ? "Type" : "类型"}><select name="kind" className={fieldClass}><option value="short">{l.short}</option><option value="essay">{l.essay}</option></select></Field><Field label={l.thinking}><textarea name="thinking" className={areaClass} /></Field><Field label={l.keywords}><input name="keywords" className={fieldClass} /></Field><Field label={l.reference}><textarea name="reference" className={areaClass} /></Field><Field label={l.source}><input name="source" className={fieldClass} /></Field></> : null}{modal === "note" ? <Field label={l.notes}><textarea name="content" className={areaClass} /></Field> : null}<Button type="submit">{l.save}</Button></form></Modal> : null}
  </section>;
}
