"use client";

import { useEffect, useState } from "react";
import { Button, Card, SectionHeader } from "@/components/ui";
import type { Locale } from "@/i18n/config";
import { CLOUD_SYNC_METADATA_KEY, CLOUD_SYNC_STATUS_EVENT, clearCloudMetadata, cloudPayload, deviceId, writeCloudMetadata, type CloudSyncStatus } from "@/data/browser/cloud-state-sync";
import { migrateBetaState } from "@/data/browser";
import { useBetaData } from "@/providers";
import { BetaPage, fieldClass } from "./shared";
import { CLOUD_SYNC_NOW_EVENT } from "./cloud-sync-auto";

type Backup={id:string;revision:number;reason:string;created_at:string};
const text={"zh-CN":{title:"账户、同步与备份",description:"使用个人恢复密钥连接云端。当前浏览器继续离线可用，连接后会自动同步到你的其他设备。",create:"创建个人云账户",key:"恢复密钥",keyHint:"这是唯一的登录凭据。请保存到密码管理器；系统无法替你找回。",saved:"我已安全保存恢复密钥",activate:"启用云同步",connect:"连接已有账户",signIn:"登录并同步",logout:"断开此设备",sync:"立即同步",backup:"创建云备份",backups:"云端恢复点",restore:"恢复此版本",connected:"已连接",disconnected:"仅本地模式",syncing:"正在同步…",synced:"云端已是最新状态",failed:"同步失败，请稍后重试。",empty:"暂无云备份。",confirm:"恢复会创建一个新版本并同步到当前设备。继续吗？"},en:{title:"Account, sync and backup",description:"Connect with a personal recovery key. This browser stays available offline and syncs automatically across your devices.",create:"Create personal cloud account",key:"Recovery key",keyHint:"This is your only sign-in credential. Save it in a password manager; it cannot be recovered for you.",saved:"I saved the recovery key safely",activate:"Enable cloud sync",connect:"Connect an existing account",signIn:"Sign in and sync",logout:"Disconnect this device",sync:"Sync now",backup:"Create cloud backup",backups:"Cloud restore points",restore:"Restore this version",connected:"Connected",disconnected:"Local-only mode",syncing:"Syncing…",synced:"Cloud is up to date",failed:"Sync failed. Try again later.",empty:"No cloud backups yet.",confirm:"Restoring creates a new cloud revision and syncs it to this device. Continue?"}};
function recoveryKey(){const bytes=crypto.getRandomValues(new Uint8Array(32));return `plos-${btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}`;}
export function CloudAccountPanel({locale}:{locale:Locale}){const l=text[locale];const {state,replaceState}=useBetaData();const [connected,setConnected]=useState(false);const [accountId,setAccountId]=useState("");const [key,setKey]=useState("");const [createdKey,setCreatedKey]=useState("");const [confirmed,setConfirmed]=useState(false);const [status,setStatus]=useState<CloudSyncStatus>({status:"disconnected"});const [backups,setBackups]=useState<Backup[]>([]);const [error,setError]=useState("");
  async function refresh(){const response=await fetch("/api/account/session",{cache:"no-store"});const body=await response.json() as {connected?:boolean;accountId?:string};setConnected(Boolean(body.connected));setAccountId(body.accountId??"");if(body.connected){const list=await fetch("/api/account/backups",{cache:"no-store"});if(list.ok)setBackups((await list.json() as {items:Backup[]}).items);}}
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);const listener=(event:Event)=>setStatus((event as CustomEvent<CloudSyncStatus>).detail);window.addEventListener(CLOUD_SYNC_STATUS_EVENT,listener);return()=>{window.clearTimeout(timer);window.removeEventListener(CLOUD_SYNC_STATUS_EVENT,listener);};},[]);
  async function create(){setError("");const value=createdKey;const id=deviceId();const response=await fetch("/api/account/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recoveryKey:value,state:cloudPayload(state),deviceId:id})});if(!response.ok){setError(locale==="en"?"Could not create the account.":"无法创建账户，请确认云端 migration 已部署。");return;}const body=await response.json() as {accountId:string;revision:number};writeCloudMetadata({accountId:body.accountId,deviceId:id,revision:body.revision});setConnected(true);setAccountId(body.accountId);setStatus({status:"synced",revision:body.revision});void refresh();}
  async function login(){setError("");const response=await fetch("/api/account/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recoveryKey:key.trim()})});if(!response.ok){setError(locale==="en"?"Invalid recovery key or cloud unavailable.":"恢复密钥无效或云端暂不可用。");return;}const body=await response.json() as {accountId:string};localStorage.setItem(CLOUD_SYNC_METADATA_KEY,JSON.stringify({accountId:body.accountId,deviceId:crypto.randomUUID(),revision:0}));setConnected(true);setAccountId(body.accountId);window.dispatchEvent(new Event(CLOUD_SYNC_NOW_EVENT));void refresh();}
  async function logout(){await fetch("/api/account/session",{method:"DELETE"});clearCloudMetadata();setConnected(false);setAccountId("");setStatus({status:"disconnected"});}
  async function backup(){const response=await fetch("/api/account/backups",{method:"POST"});if(response.ok)void refresh();}
  async function restore(item:Backup){if(!window.confirm(l.confirm))return;const metadata=JSON.parse(localStorage.getItem(CLOUD_SYNC_METADATA_KEY)??"null") as {deviceId?:string}|null;const response=await fetch(`/api/account/backups/${item.id}/restore`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({deviceId:metadata?.deviceId??crypto.randomUUID()})});if(!response.ok){setError(l.failed);return;}const cloud=await fetch("/api/account/state",{cache:"no-store"});const body=await cloud.json() as {accountId:string;revision:number;state:unknown};try{replaceState(migrateBetaState(body.state));}catch{setError(l.failed);return;}writeCloudMetadata({accountId:body.accountId,deviceId:metadata?.deviceId??crypto.randomUUID(),revision:body.revision});setStatus({status:"synced",revision:body.revision});void refresh();}
  const statusLabel=status.status==="syncing"?l.syncing:status.status==="synced"?l.synced:status.status==="failed"?l.failed:connected?l.connected:l.disconnected;
  return <BetaPage title={l.title} description={l.description}><Card><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="type-label text-primary">{statusLabel}</p>{accountId?<p className="type-caption mt-1 text-muted">{accountId}</p>:null}</div>{connected?<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>window.dispatchEvent(new Event(CLOUD_SYNC_NOW_EVENT))}>{l.sync}</Button><Button variant="secondary" onClick={backup}>{l.backup}</Button><Button variant="ghost" onClick={logout}>{l.logout}</Button></div>:null}</div></Card>{!connected?<div className="grid gap-6 desktop:grid-cols-2"><Card><SectionHeader title={l.create}/>{createdKey?<div className="mt-5"><label className="type-label text-primary">{l.key}</label><textarea className={`${fieldClass} mt-2 min-h-24 font-mono`} readOnly value={createdKey}/><p className="type-small mt-3 text-secondary">{l.keyHint}</p><label className="mt-4 flex gap-3 type-small text-primary"><input type="checkbox" checked={confirmed} onChange={(event)=>setConfirmed(event.target.checked)}/>{l.saved}</label><Button className="mt-4" disabled={!confirmed} onClick={create}>{l.activate}</Button></div>:<Button className="mt-5" onClick={()=>{setCreatedKey(recoveryKey());setConfirmed(false);}}>{l.create}</Button>}</Card><Card><SectionHeader title={l.connect}/><label className="type-label mt-5 block text-primary" htmlFor="recovery-key">{l.key}</label><input id="recovery-key" className={`${fieldClass} mt-2 font-mono`} type="password" autoComplete="off" value={key} onChange={(event)=>setKey(event.target.value)}/><Button className="mt-4" disabled={!key.trim()} onClick={login}>{l.signIn}</Button></Card></div>:<section><SectionHeader title={l.backups}/><div className="mt-5 grid gap-3">{backups.length?backups.map((item)=><Card key={item.id} padding="sm"><div className="flex items-center justify-between gap-3"><div><p className="type-label text-primary">Revision {item.revision}</p><p className="type-caption mt-1 text-muted">{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.created_at))} · {item.reason}</p></div><Button size="sm" variant="secondary" onClick={()=>restore(item)}>{l.restore}</Button></div></Card>):<Card><p className="type-body text-secondary">{l.empty}</p></Card>}</div></section>}{error?<p role="alert" className="type-small text-error">{error}</p>:null}</BetaPage>}
