"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { Button, Card, SectionHeader } from "@/components/ui";
import type { Locale } from "@/i18n/config";
import { getBetaMessages } from "@/i18n/beta-messages";
import { useBetaData } from "@/providers";
import { BetaPage, EmptyState, formatDateTime, localDate } from "./shared";
import { PomodoroPanel } from "./pomodoro";

export function BetaDashboard({ locale }: { locale: Locale }) {
  const m=getBetaMessages(locale); const {state,mutate}=useBetaData(); const today=localDate();
  const sessions=state.studySessions.filter((s)=>localDate(new Date(s.startedAt))===today&&s.completed);
  const tasks=state.tasks.filter((t)=>t.date===today); const reviews=state.reviewItems.filter((r)=>r.status==="due"&&r.dueDate<=today);
  const minutes=sessions.reduce((n,s)=>n+s.durationMinutes,0); const recent=[...state.studySessions].sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,5);
  const bySubject=state.subjects.map((subject)=>({subject,minutes:sessions.filter((s)=>s.subjectId===subject.id).reduce((n,s)=>n+s.durationMinutes,0)}));
  return <BetaPage title={m.dashboard.title} description={`${new Intl.DateTimeFormat(locale,{dateStyle:"full"}).format(new Date())} · ${m.dashboard.subtitle}`}>
    <div className="grid grid-cols-3 overflow-hidden rounded-xl border border-border bg-surface shadow-soft">{[[m.dashboard.study,`${minutes} ${m.minutes}`],[m.dashboard.tasks,`${tasks.filter((t)=>t.status==="completed").length} / ${tasks.length}`],[m.dashboard.reviews,String(reviews.length)]].map(([label,value],i)=><div key={label} className={`min-w-0 p-4 tablet:p-6 ${i?"border-l border-border":""}`}><p className="type-caption truncate text-muted">{label}</p><p className="mt-2 text-xl font-semibold text-primary tablet:text-2xl">{value}</p></div>)}</div>
    <div className="grid gap-10 desktop:grid-cols-[1.35fr_.8fr] desktop:items-start"><div className="grid gap-10"><section><SectionHeader title={m.dashboard.tasks} description={m.plan.subtitle}/><div className="mt-5 grid gap-3">{tasks.length?tasks.slice(0,5).map((task)=><Card key={task.id} padding="sm"><div className="flex items-center justify-between gap-3"><div><p className={`type-label text-primary ${task.status==="completed"?"line-through opacity-60":""}`}>{task.title}</p><p className="type-caption mt-1 text-muted">{task.plannedMinutes} {m.minutes} · {task.actualMinutes} {m.plan.actual}</p></div><Button size="sm" variant={task.status==="completed"?"secondary":"primary"} onClick={()=>mutate((draft)=>{const item=draft.tasks.find((x)=>x.id===task.id);if(item){item.status=item.status==="completed"?"todo":"completed";item.completedAt=item.status==="completed"?new Date().toISOString():undefined;}})}>{task.status==="completed"?m.plan.todo:m.plan.done}</Button></div></Card>):<EmptyState>{m.empty}</EmptyState>}<Link href={`/${locale}/plan`} className="type-label mt-4 inline-flex min-h-11 items-center text-accent hover:underline">{m.plan.title} →</Link></div></section><section><SectionHeader title={m.focus.title} description={m.focus.subtitle}/><div className="mt-5"><PomodoroPanel locale={locale}/></div></section><section><SectionHeader title={m.dashboard.subjects}/><div className="mt-5 grid gap-3 tablet:grid-cols-3">{bySubject.map(({subject,minutes})=><Link key={subject.id} href={`/${locale}/${subject.slug==="psychology"?"psychology":subject.slug==="politics"?"politics":"vocabulary"}`}><Card className="h-full transition-colors hover:border-border-strong"><h3 className="type-h3 text-primary">{locale==="en"?subject.nameEn:subject.name}</h3><p className="type-small mt-5 text-secondary">{minutes} {m.minutes}</p></Card></Link>)}</div></section></div>
      <aside className="grid gap-10 tablet:grid-cols-2 desktop:grid-cols-1"><section><SectionHeader title={m.dashboard.reviews}/><Card className="mt-5" padding="sm">{reviews.length?<div className="divide-y divide-border">{reviews.slice(0,5).map((r)=><div key={r.id} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0"><div><p className="type-label text-primary">{r.title}</p><p className="type-caption mt-1 text-muted">{r.dueDate}</p></div><Button size="sm" variant="secondary" onClick={()=>mutate((draft)=>{const item=draft.reviewItems.find((x)=>x.id===r.id);if(item){item.status="completed";item.completedAt=new Date().toISOString();}})}>{m.plan.done}</Button></div>)}</div>:<p className="type-body text-secondary">{m.empty}</p>}</Card></section><section><SectionHeader title={m.news.title}/><Card className="mt-5" variant="muted"><p className="type-label text-primary">{m.dashboard.noNews}</p><p className="type-small mt-2 text-secondary">{m.dashboard.newsHelp}</p></Card></section><section><SectionHeader title={m.dashboard.recent}/><Card className="mt-5" padding="sm">{recent.length?<div className="divide-y divide-border">{recent.map((s)=>{const subject=state.subjects.find((x)=>x.id===s.subjectId);return <div key={s.id} className="py-3 first:pt-0 last:pb-0"><p className="type-label text-primary">{subject?(locale==="en"?subject.nameEn:subject.name):m.focus.title}</p><p className="type-caption mt-1 text-muted">{s.durationMinutes} {m.minutes} · {formatDateTime(s.startedAt,locale)}</p></div>;})}</div>:<p className="type-body text-secondary">{m.empty}</p>}</Card></section></aside>
    </div><DataManagement locale={locale}/>
  </BetaPage>;
}

function DataManagement({locale}:{locale:Locale}){const m=getBetaMessages(locale);const {exportJson,importJson,clearAll}=useBetaData();const input=useRef<HTMLInputElement>(null);const [error,setError]=useState("");function download(){const blob=new Blob([exportJson()],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`personal-learning-os-${localDate()}.json`;a.click();URL.revokeObjectURL(url);}async function upload(file?:File){if(!file)return;const result=importJson(await file.text());setError(result.ok?"":m.data.invalid);}function clear(){if(window.confirm(m.data.confirmClear)&&window.confirm(m.data.confirmClear))clearAll();}return <section><SectionHeader title={m.data.title} description={m.data.local}/><Card className="mt-5" padding="sm"><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={download}>{m.data.export}</Button><Button variant="secondary" onClick={()=>input.current?.click()}>{m.data.import}</Button><Button variant="danger" onClick={clear}>{m.data.clear}</Button><input ref={input} hidden type="file" accept="application/json" onChange={(e)=>void upload(e.target.files?.[0])}/></div>{error?<p className="type-small mt-3 text-error" role="alert">{error}</p>:null}</Card></section>}
