"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import type { Locale } from "@/i18n/config";
import { getBetaMessages } from "@/i18n/beta-messages";
import { useBetaData } from "@/providers";
import { fieldClass } from "./shared";

export function GlobalSearch({locale}:{locale:Locale}){const m=getBetaMessages(locale);const {state}=useBetaData();const [query,setQuery]=useState("");const q=query.trim().toLowerCase();const results=useMemo(()=>{if(q.length<2)return[];const items=[...state.knowledgePoints.map((x)=>({id:x.id,title:locale==="en"?x.titleEn:x.title,body:`${x.coreConcept} ${x.personalNote}`,href:x.subjectId==="subject-politics"?"politics":"psychology"})),...state.vocabulary.map((x)=>({id:x.id,title:x.word,body:`${x.meaning} ${x.example}`,href:"vocabulary"})),...state.notes.map((x)=>({id:x.id,title:x.title,body:x.content,href:"knowledge"})),...state.books.map((x)=>({id:x.id,title:x.title,body:`${x.author} ${x.notes}`,href:"books"})),...state.resources.map((x)=>({id:x.id,title:x.name,body:`${x.description} ${x.tags.join(" ")}`,href:"world"}))];return items.filter((x)=>`${x.title} ${x.body}`.toLowerCase().includes(q)).slice(0,8);},[q,state,locale]);return <div className="relative mx-auto w-full max-w-xl px-4 pt-4 tablet:px-6 desktop:px-8"><label className="sr-only" htmlFor="global-search">{m.search}</label><input id="global-search" className={fieldClass} value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={`${m.search}…`}/>{q.length>=2?<div className="absolute left-4 right-4 top-[4.25rem] z-40 rounded-lg border border-border bg-surface-raised p-2 shadow-card tablet:left-6 tablet:right-6 desktop:left-8 desktop:right-8">{results.length?results.map((r)=><Link key={`${r.href}-${r.id}`} href={`/${locale}/${r.href}`} onClick={()=>setQuery("")} className="block rounded-md px-3 py-2 hover:bg-surface-muted"><span className="type-label text-primary">{r.title}</span><span className="type-caption ml-2 text-muted">{r.href}</span></Link>):<p className="type-small p-3 text-muted">{m.noResults}</p>}</div>:null}</div>}
