"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import type { Locale } from "@/i18n/config";
import { getBetaMessages } from "@/i18n/beta-messages";
import { useBetaData } from "@/providers";
import { buildCurriculumCatalog } from "@/domain";
import { fieldClass } from "./shared";

interface SearchResult { id:string; title:string; hierarchy:string; body:string; href:string; kind:string; }

export function GlobalSearch({locale}:{locale:Locale}) {
  const m=getBetaMessages(locale); const {state}=useBetaData(); const [query,setQuery]=useState(""); const q=query.trim().toLowerCase();
  const results=useMemo(()=>{
    if(q.length<2)return[];
    const catalog=buildCurriculumCatalog(state); const items:SearchResult[]=[];
    for(const course of catalog.curricula) items.push({id:course.id,title:locale==="en"?course.titleEn:course.title,hierarchy:locale==="en"?"Course":"教材 / 课程",body:`${course.description} ${course.descriptionEn} ${course.author??""}`,href:`learn/${course.id}`,kind:locale==="en"?"Course":"课程"});
    for(const chapter of catalog.chapters){const course=catalog.curricula.find((item)=>item.id===chapter.curriculumId);items.push({id:chapter.id,title:locale==="en"?chapter.titleEn:chapter.title,hierarchy:`${locale==="en"?course?.titleEn:course?.title} → ${locale==="en"?"Chapter":"章"}`,body:`${chapter.description} ${chapter.descriptionEn}`,href:`learn/${chapter.curriculumId}`,kind:locale==="en"?"Chapter":"章"});}
    for(const section of catalog.sections){const chapter=catalog.chapters.find((item)=>item.id===section.chapterId);const course=catalog.curricula.find((item)=>item.id===chapter?.curriculumId);if(!chapter||!course)continue;items.push({id:section.id,title:locale==="en"?section.titleEn:section.title,hierarchy:`${locale==="en"?course.titleEn:course.title} → ${locale==="en"?chapter.titleEn:chapter.title}`,body:section.knowledgePointIds.join(" "),href:`learn/${course.id}/${chapter.id}/${section.id}`,kind:locale==="en"?"Section":"节"});}
    for(const point of state.knowledgePoints){const section=catalog.sections.find((item)=>item.knowledgePointIds.includes(point.id));const chapter=catalog.chapters.find((item)=>item.id===section?.chapterId);const course=catalog.curricula.find((item)=>item.id===chapter?.curriculumId);items.push({id:point.id,title:locale==="en"?point.titleEn:point.title,hierarchy:course&&chapter&&section?`${locale==="en"?course.titleEn:course.title} → ${locale==="en"?chapter.titleEn:chapter.title} → ${locale==="en"?section.titleEn:section.title}`:(locale==="en"?"Knowledge point":"知识点"),body:`${point.coreConcept} ${point.personalNote} ${(point.examFocus??[]).join(" ")}`,href:course&&chapter&&section?`learn/${course.id}/${chapter.id}/${section.id}#knowledge-${point.id}`:"learn",kind:locale==="en"?"Knowledge":"知识点"});}
    items.push(...state.questions.map((x)=>({id:x.id,title:x.stem,hierarchy:x.isOfficial&&x.year?`${locale==="en"?"Verified past exam":"已核验真题"} · ${x.year}`:(locale==="en"?"System practice":"系统原创练习"),body:`${x.explanation} ${x.tags.join(" ")}`,href:"questions",kind:locale==="en"?"Question":"题目"})),...state.vocabulary.map((x)=>({id:x.id,title:x.word,hierarchy:locale==="en"?"English → Vocabulary":"英语 → 单词",body:`${x.meaning} ${x.example}`,href:"english",kind:locale==="en"?"Word":"单词"})),...state.englishContent.map((x)=>({id:x.id,title:x.title,hierarchy:`${locale==="en"?"English":"英语"} → ${x.kind}`,body:`${x.content} ${x.note}`,href:"english",kind:x.kind})),...state.recitations.map((x)=>({id:x.id,title:x.title,hierarchy:locale==="en"?"Recitation":"背诵",body:x.content,href:"recitation",kind:locale==="en"?"Recitation":"背诵"})),...state.notes.map((x)=>({id:x.id,title:x.title,hierarchy:locale==="en"?"Knowledge base":"知识库",body:x.content,href:"knowledge",kind:locale==="en"?"Note":"笔记"})),...state.wrongQuestions.map((x)=>{const question=state.questions.find((item)=>item.id===x.questionId);return{id:x.id,title:question?.stem??x.id,hierarchy:locale==="en"?"Mistakes":"错题本",body:question?.explanation??"",href:"mistakes",kind:locale==="en"?"Mistake":"错题"};}));
    return items.filter((item)=>`${item.title} ${item.hierarchy} ${item.body}`.toLowerCase().includes(q)).slice(0,12);
  },[locale,q,state]);
  return <div className="relative mx-auto w-full max-w-xl px-4 pt-4 tablet:px-6 desktop:px-8"><label className="sr-only" htmlFor="global-search">{m.search}</label><input id="global-search" className={fieldClass} value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={`${m.search}…`}/>{q.length>=2?<div className="absolute left-4 right-4 top-[4.25rem] z-40 max-h-[70vh] overflow-y-auto rounded-lg border border-border bg-surface-raised p-2 shadow-card tablet:left-6 tablet:right-6 desktop:left-8 desktop:right-8">{results.length?results.map((result)=><Link key={`${result.kind}-${result.id}`} href={`/${locale}/${result.href}`} onClick={()=>setQuery("")} className="block rounded-md px-3 py-2 hover:bg-surface-muted"><span className="type-label text-primary">{result.title}</span><span className="type-caption ml-2 text-muted">{result.kind}</span><span className="mt-1 block truncate type-caption text-muted">{result.hierarchy}</span></Link>):<p className="type-small p-3 text-muted">{m.noResults}</p>}</div>:null}</div>;
}
