"use client";

import { useEffect, useState } from "react";
import { Badge, Button, Card } from "@/components/ui";
import type { PlanningDay, PlanningProfile } from "@/domain/beta";
import { parsePlanChanges, type PlanChange, type PlanContext } from "@/domain/planning/ai-plan";
import type { Locale } from "@/i18n/config";
import { addLocalDays } from "@/lib/date";
import { useBetaData } from "@/providers";
import { Field, fieldClass, localDate, nowEntity, uid } from "./shared";

function defaultProfile(): PlanningProfile {
  return { goal: "", dailyMinutes: 120, weeklyGoalMinutes: 600, subjectPriorities: {}, weakSubjectIds: [], workHours: "", sleepHours: "", restPreferences: "", days: [], updatedAt: new Date().toISOString() };
}

export function PlanningPanel({ locale }: { locale: Locale }) {
  const en = locale === "en"; const { state, mutate } = useBetaData(); const [profile, setProfile] = useState<PlanningProfile>(() => state.planningProfile ?? defaultProfile());
  const [configured, setConfigured] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const [instruction, setInstruction] = useState(""); const [changes, setChanges] = useState<PlanChange[]>([]);
  const today = localDate(); const dates = Array.from({ length: 7 }, (_, index) => addLocalDays(today, index));
  useEffect(() => { void fetch("/api/ai-plan").then((response) => response.json()).then((value: { configured?: boolean }) => setConfigured(Boolean(value.configured))).catch(() => setConfigured(false)); }, []);
  function updateDay(date: string, patch: Partial<PlanningDay>) {
    setProfile((current) => { const prior = current.days.find((day) => day.date === date) ?? { date, kind: "work" as const, availableMinutes: current.dailyMinutes, energy: "medium" as const };
      return { ...current, days: [...current.days.filter((day) => day.date !== date), { ...prior, ...patch }] }; });
  }
  function save() {
    if (profile.dailyMinutes < 0 || profile.dailyMinutes > 960 || profile.days.some((day) => day.availableMinutes < 0 || day.availableMinutes > 960)) { setMessage(en ? "Daily time must be 0–960 minutes." : "每天可学习时间需在 0–960 分钟之间。"); return; }
    const next = { ...profile, updatedAt: new Date().toISOString() };
    mutate((draft) => { draft.planningProfile = next; }); setMessage(en ? "Planning profile saved in this browser." : "规划资料已保存到当前浏览器。"); setChanges([]);
  }
  function context(): PlanContext { return { today, subjectIds: state.subjects.map((subject) => subject.id),
    tasks: state.tasks.map(({ id, title, subjectId, date, plannedMinutes, actualMinutes, status, planningControl }) => ({ id, title, subjectId, date, plannedMinutes, actualMinutes, status, planningControl })),
    profile: state.planningProfile ?? profile,
    recentStudy: state.studySessions.slice(-30).map((session) => ({ subjectId: session.subjectId, minutes: session.durationMinutes, date: localDate(new Date(session.startedAt)) })),
    dueReviews: state.reviewItems.filter((item) => item.status === "due").slice(0, 30).map((item) => ({ kind: item.kind, title: item.title, dueDate: item.dueDate })),
    mastery: state.subjects.map((subject) => { const points = state.knowledgePoints.filter((point) => point.subjectId === subject.id); return { subjectId: subject.id,
      newCount: points.filter((point) => point.mastery === "new").length, learningCount: points.filter((point) => point.mastery === "learning" || point.mastery === "reviewing").length,
      masteredCount: points.filter((point) => point.mastery === "mastered").length }; }),
  }; }
  async function generate() {
    if (!configured || !state.planningProfile) return;
    setBusy(true); setMessage(""); setChanges([]);
    try { const response = await fetch("/api/ai-plan", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ context: context(), instruction }) });
      const data: { changes?: PlanChange[]; error?: string } = await response.json();
      if (!response.ok || !Array.isArray(data.changes)) throw new Error(data.error);
      setChanges(data.changes); if (!data.changes.length) setMessage(en ? "No safe plan changes were suggested." : "这次没有建议安全的计划变更。");
    } catch { setMessage(en ? "Could not generate a valid plan. Existing tasks were not changed." : "未能生成有效计划，现有任务未更改。"); }
    finally { setBusy(false); }
  }
  function apply() {
    const validated = parsePlanChanges({ changes }, context());
    if (!validated) { setMessage(en ? "Plan changed since preview. Generate again." : "预览后计划已有变化，请重新生成。"); setChanges([]); return; }
    mutate((draft) => { for (const change of validated) {
      if (change.kind === "add") draft.tasks.push({ ...nowEntity(uid("task"), draft.ownerId), title: change.title, description: change.reason, subjectId: change.subjectId,
        date: change.date, plannedMinutes: change.minutes, actualMinutes: 0, priority: "medium", status: "todo", sourceType: "ai", planningControl: "adjustable" });
      else { const task = draft.tasks.find((item) => item.id === change.taskId && item.planningControl === "adjustable" && item.status !== "completed"); if (task) { task.date = change.date; task.updatedAt = new Date().toISOString(); } }
    } }); setChanges([]); setMessage(en ? "Confirmed changes saved to local tasks." : "已确认，变更已写入本地任务。");
  }
  return <section className="grid gap-4"><Card padding="sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="type-h2 text-primary">{en ? "Planning profile" : "学习规划资料"}</h2><p className="type-small mt-2 text-secondary">{en ? "Describe your goal, capacity and shifts. Your manual tasks stay under your control." : "记录目标、可用时间和排班；手动任务始终由你控制。"}</p></div><Button size="sm" variant="secondary" onClick={save}>{en ? "Save profile" : "保存资料"}</Button></div>
    <div className="mt-5 grid gap-4 tablet:grid-cols-2"><Field label={en ? "Goal / exam" : "目标 / 考试"}><input className={fieldClass} value={profile.goal} maxLength={160} onChange={(event) => setProfile({ ...profile, goal: event.target.value })} /></Field><Field label={en ? "Exam date" : "考试日期"}><input type="date" className={fieldClass} value={profile.examDate ?? ""} onChange={(event) => setProfile({ ...profile, examDate: event.target.value || undefined })} /></Field><Field label={en ? "Default daily minutes" : "默认每日可学分钟"}><input type="number" min={0} max={960} className={fieldClass} value={profile.dailyMinutes} onChange={(event) => setProfile({ ...profile, dailyMinutes: Number(event.target.value) })} /></Field><Field label={en ? "Weekly goal minutes" : "每周目标分钟"}><input type="number" min={0} max={6720} className={fieldClass} value={profile.weeklyGoalMinutes} onChange={(event) => setProfile({ ...profile, weeklyGoalMinutes: Number(event.target.value) })} /></Field><Field label={en ? "Work hours / shift notes" : "固定工作时间 / 排班说明"}><input className={fieldClass} value={profile.workHours} maxLength={160} onChange={(event) => setProfile({ ...profile, workHours: event.target.value })} /></Field><Field label={en ? "Sleep hours" : "睡眠时间"}><input className={fieldClass} value={profile.sleepHours} maxLength={80} onChange={(event) => setProfile({ ...profile, sleepHours: event.target.value })} /></Field><Field label={en ? "Rest preferences" : "希望休息时间"}><input className={fieldClass} value={profile.restPreferences} maxLength={160} onChange={(event) => setProfile({ ...profile, restPreferences: event.target.value })} /></Field><Field label={en ? "Weak subjects" : "薄弱科目"}><select multiple className={`${fieldClass} min-h-28`} value={profile.weakSubjectIds} onChange={(event) => setProfile({ ...profile, weakSubjectIds: Array.from(event.target.selectedOptions, (option) => option.value) })}>{state.subjects.map((subject) => <option key={subject.id} value={subject.id}>{en ? subject.nameEn : subject.name}</option>)}</select></Field></div>
    <h3 className="type-h3 mt-6 text-primary">{en ? "Next 7 days" : "未来 7 天排班"}</h3><div className="mt-3 grid gap-3">{dates.map((date) => { const day = profile.days.find((entry) => entry.date === date); return <div key={date} className="grid gap-2 rounded-md border border-border p-3 tablet:grid-cols-[8rem_1fr_1fr_1fr]"><span className="type-label self-center text-primary">{date}</span><Field label={en ? "Day type" : "日类型"}><select className={fieldClass} value={day?.kind ?? "work"} onChange={(event) => updateDay(date, { kind: event.target.value as PlanningDay["kind"] })}>{(["work", "rest", "half", "special"] as const).map((kind) => <option key={kind} value={kind}>{en ? ({ work: "Work", rest: "Rest", half: "Half day", special: "Special" })[kind] : ({ work: "上班", rest: "休息", half: "半天", special: "特殊安排" })[kind]}</option>)}</select></Field><Field label={en ? "Available minutes" : "可学分钟"}><input type="number" min={0} max={960} className={fieldClass} value={day?.availableMinutes ?? profile.dailyMinutes} onChange={(event) => updateDay(date, { availableMinutes: Number(event.target.value) })} /></Field><Field label={en ? "Energy" : "精力"}><select className={fieldClass} value={day?.energy ?? "medium"} onChange={(event) => updateDay(date, { energy: event.target.value as PlanningDay["energy"] })}><option value="low">{en ? "Low" : "低"}</option><option value="medium">{en ? "Medium" : "中"}</option><option value="high">{en ? "High" : "高"}</option></select></Field></div>; })}</div><div className="mt-4 grid gap-3 tablet:grid-cols-2">{dates.map((date) => <Field key={date} label={`${date} · ${en ? "Work hours" : "工作时间"}`}><input className={fieldClass} value={profile.days.find((entry) => entry.date === date)?.workHours ?? ""} onChange={(event) => updateDay(date, { workHours: event.target.value })} placeholder={en ? "e.g. 09:00–18:00" : "如 09:00–18:00"} /></Field>)}</div><h3 className="type-h3 mt-6 text-primary">{en ? "Subject priorities" : "科目优先级"}</h3><div className="mt-3 grid gap-3 tablet:grid-cols-2">{state.subjects.map((subject) => <Field key={subject.id} label={en ? subject.nameEn : subject.name}><select className={fieldClass} value={profile.subjectPriorities[subject.id] ?? 3} onChange={(event) => setProfile({ ...profile, subjectPriorities: { ...profile.subjectPriorities, [subject.id]: Number(event.target.value) } })}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value}</option>)}</select></Field>)}</div><Button className="mt-4" variant="secondary" onClick={save}>{en ? "Save profile" : "保存资料"}</Button></Card>
    {state.tasks.length ? <Card padding="sm"><h2 className="type-h3 text-primary">{en ? "AI adjustment permissions" : "任务的 AI 调整权限"}</h2><p className="type-small mt-2 text-secondary">{en ? "Only tasks explicitly marked adjustable may be moved by an AI proposal." : "只有明确设为“AI 可调整”的任务才允许在计划预览中移动。"}</p><div className="mt-4 grid gap-3">{state.tasks.filter((task) => task.status !== "completed").slice(0, 30).map((task) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-border p-3"><span className="type-small text-primary">{task.title} · {task.date}</span><Field label={en ? "Control" : "调整权限"} className="min-w-40"><select className={fieldClass} value={task.planningControl ?? "manual"} onChange={(event) => mutate((draft) => { const record = draft.tasks.find((item) => item.id === task.id); if (record) record.planningControl = event.target.value as "manual" | "adjustable" | "locked"; })}><option value="manual">{en ? "Manual" : "手动"}</option><option value="adjustable">{en ? "AI adjustable" : "AI 可调整"}</option><option value="locked">{en ? "Locked" : "锁定"}</option></select></Field></div>)}</div></Card> : null}
    <Card padding="sm"><div className="flex flex-wrap items-center gap-3"><h2 className="type-h2 text-primary">{en ? "AI study plan" : "AI 学习计划"}</h2><Badge variant={configured ? "accent" : "neutral"}>{configured ? (en ? "Provider ready" : "服务已配置") : (en ? "Not configured" : "尚未配置 AI 服务")}</Badge></div><p className="type-small mt-2 text-secondary">{en ? "AI proposals use your saved profile and current tasks. Preview and confirm every change." : "AI 使用已保存资料、现有任务与实际学习时长生成建议；每项变更都先预览再确认。"}</p>{configured ? <div className="mt-4 grid gap-3"><Field label={en ? "Replanning request" : "一句话重新规划"}><input className={fieldClass} maxLength={500} value={instruction} onChange={(event) => setInstruction(event.target.value)} placeholder={en ? "I work late today; plan a lighter evening" : "今天加班到 8 点，只安排 1 小时"} /></Field><Button disabled={!state.planningProfile || busy} onClick={() => void generate()}>{busy ? (en ? "Generating…" : "生成中…") : (en ? "Generate plan preview" : "生成计划预览")}</Button>{!state.planningProfile ? <p className="type-caption text-muted">{en ? "Save your profile first." : "请先保存规划资料。"}</p> : null}</div> : <p className="type-small mt-4 text-muted">{en ? "Configure AI_API_URL, AI_API_KEY and AI_MODEL as server secrets to enable generation. Manual planning remains available." : "需在服务端配置 AI_API_URL、AI_API_KEY、AI_MODEL；手动计划仍可正常使用。"}</p>}
      {changes.length ? <div className="mt-5 grid gap-2"><h3 className="type-h3 text-primary">{en ? "Proposed changes" : "将执行以下变更"}</h3>{changes.map((change, index) => <div key={`${change.kind}-${index}`} className="rounded-md border border-border bg-surface-muted p-3"><p className="type-label text-primary">{change.kind === "add" ? `${en ? "Add" : "新增"} · ${change.title} · ${change.minutes} min · ${change.date}` : `${en ? "Move" : "移动"} · ${state.tasks.find((task) => task.id === change.taskId)?.title ?? ""} → ${change.date}`}</p><p className="type-small mt-1 text-secondary">{change.reason}</p></div>)}<div className="mt-2 flex gap-2"><Button onClick={apply}>{en ? "Confirm changes" : "确认变更"}</Button><Button variant="secondary" onClick={() => setChanges([])}>{en ? "Cancel" : "取消"}</Button></div></div> : null}{message ? <p role="status" className="type-small mt-4 text-secondary">{message}</p> : null}</Card>
  </section>;
}
