"use client";
import { useEffect } from "react";
import { analyzeWeakPoints } from "@/domain/analytics/weak-points";
import { buildSmartPlan } from "@/domain/planning/smart-plan";
import { useBetaData } from "@/providers";
import { addLocalDays } from "@/lib/date";
import { getDashboardAnalytics } from "./dashboard-analytics";
import { localDate } from "./shared";
export function PlanningContextAutoSync(){const{state}=useBetaData();useEffect(()=>{const timer=window.setTimeout(()=>{const today=localDate();const weekStart=addLocalDays(today,-6);const monthStart=addLocalDays(today,-29);const weak=analyzeWeakPoints(state,today);const analytics=getDashboardAnalytics(state,today);const sessions=state.studySessions.filter((item)=>item.completed).map((item)=>({...item,localDate:localDate(new Date(item.endedAt))}));const context={generatedAt:new Date().toISOString(),today,planningProfile:state.planningProfile??null,todayPlan:buildSmartPlan(state,today),recent7Days:{from:weekStart,minutes:analytics.week.days.reduce((sum,item)=>sum+item.minutes,0),daily:analytics.week.days,subjects:analytics.week.subjects,taskCompletionRate:analytics.week.completionRate},recent30Days:{from:monthStart,minutes:sessions.filter((item)=>item.localDate>=monthStart&&item.localDate<=today).reduce((sum,item)=>sum+item.durationMinutes,0),sessions:sessions.filter((item)=>item.localDate>=monthStart&&item.localDate<=today).length},overdueTasks:state.tasks.filter((item)=>item.status!=="completed"&&item.date<today).map(({id,title,subjectId,chapterId,date,plannedMinutes,priority})=>({id,title,subjectId,chapterId,date,plannedMinutes,priority})).slice(0,50),reviewQueue:state.reviewItems.filter((item)=>item.status==="due").sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,100),weakKnowledgePoints:weak.weakKnowledgePoints.slice(0,50),weakSubjects:weak.weakSubjects,weakChapters:weak.weakChapters};void fetch("/api/external-writes/planning-context",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(context)}).catch(()=>undefined);},2500);return()=>window.clearTimeout(timer);},[state]);return null;}
