"use client";

import Link from "next/link";
import { useRef, useState, type PointerEvent } from "react";
import { Button } from "@/components/ui";
import type { BetaKnowledgePoint } from "@/domain/beta";
import type { CurriculumChapter, CurriculumSection } from "@/domain/learning/curriculum";
import type { Locale } from "@/i18n/config";

export function ChapterMindMap({ locale, curriculumId, chapter, sections, points }: { locale: Locale; curriculumId: string; chapter: CurriculumChapter; sections: CurriculumSection[]; points: BetaKnowledgePoint[] }) {
  const frame=useRef<HTMLDivElement>(null); const [scale,setScale]=useState(1); const [offset,setOffset]=useState({x:0,y:0}); const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
  function down(event:PointerEvent<HTMLDivElement>){drag.current={x:event.clientX,y:event.clientY,ox:offset.x,oy:offset.y};event.currentTarget.setPointerCapture(event.pointerId);}
  function move(event:PointerEvent<HTMLDivElement>){if(!drag.current)return;setOffset({x:drag.current.ox+event.clientX-drag.current.x,y:drag.current.oy+event.clientY-drag.current.y});}
  const textbookSections=sections.filter((item)=>item.kind!=="chapter_review");
  return <section><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="type-h3 text-primary">{locale==="en"?"Chapter knowledge graph":"本章思维导图"}</h3><p className="type-caption mt-1 text-muted">{locale==="en"?"Drag the canvas, zoom, or open a node.":"可拖动画布、缩放、全屏；点击节点返回对应小节。"}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={()=>setScale((value)=>Math.max(.6,value-.1))}>−</Button><Button size="sm" variant="secondary" onClick={()=>{setScale(1);setOffset({x:0,y:0});}}>100%</Button><Button size="sm" variant="secondary" onClick={()=>setScale((value)=>Math.min(1.8,value+.1))}>＋</Button><Button size="sm" variant="secondary" onClick={()=>void frame.current?.requestFullscreen()}>{locale==="en"?"Full screen":"全屏"}</Button></div></div><div ref={frame} className="mt-4 h-[34rem] overflow-hidden rounded-lg border border-border bg-surface-muted touch-none" onPointerDown={down} onPointerMove={move} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}><div className="min-h-full min-w-[70rem] p-10 transition-transform" style={{transform:`translate(${offset.x}px, ${offset.y}px) scale(${scale})`,transformOrigin:"top left"}}><div className="mx-auto w-fit rounded-lg border border-accent bg-surface-raised px-6 py-4 type-h3 text-primary">{locale==="en"?chapter.titleEn:chapter.title}</div><div className="mx-auto h-8 w-px bg-border-strong"/><div className="grid grid-cols-2 gap-8 desktop:grid-cols-3">{textbookSections.map((section)=><div key={section.id} className="rounded-lg border border-border bg-surface-raised p-4 shadow-soft"><Link draggable={false} href={`/${locale}/learn/${curriculumId}/${chapter.id}/${section.id}`} className="type-label text-primary hover:text-accent hover:underline">{locale==="en"?section.titleEn:section.title}</Link><div className="mt-3 grid gap-2">{section.knowledgePointIds.map((id)=>{const point=points.find((item)=>item.id===id);return point?<Link draggable={false} key={id} href={`/${locale}/learn/${curriculumId}/${chapter.id}/${section.id}`} className="rounded-md bg-surface-muted p-2 type-small text-secondary hover:bg-accent-soft"><span>{locale==="en"?point.titleEn:point.title}</span><span className="mt-1 block type-caption text-muted">{(point.examFocus?.[0]??point.keyPoints).slice(0,64)}</span></Link>:null;})}</div></div>)}</div></div></div></section>;
}
