"use client";
import { useRef,useState,type ChangeEvent,type PointerEvent } from "react";
import { Badge,Button,Card } from "@/components/ui";
import type { BetaKnowledgePoint,BetaQuestion,ImportedMindMapNode } from "@/domain/beta";
import type { CurriculumChapter,CurriculumSection } from "@/domain/learning/curriculum";
import { mindMapNodeCount,parseMindMapFile,type MindMapFormat } from "./mind-map-import";
import { nowEntity } from "@/features/beta/shared";
import type { Locale } from "@/i18n/config";
import { useBetaData } from "@/providers";

type Preview={sourceFileName:string;format:MindMapFormat;tree:ImportedMindMapNode};
export function ChapterMindMap({locale,curriculumId,chapter,sections,points}:{locale:Locale;curriculumId:string;chapter:CurriculumChapter;sections:CurriculumSection[];points:BetaKnowledgePoint[];questions?:BetaQuestion[]}){
 const {state,mutate}=useBetaData();const en=locale==="en";const input=useRef<HTMLInputElement>(null);const frame=useRef<HTMLDivElement>(null);const saved=state.chapterMindMaps.find(x=>x.curriculumId===curriculumId&&x.chapterId===chapter.id);
 const [preview,setPreview]=useState<Preview>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [scale,setScale]=useState(.9);const [offset,setOffset]=useState({x:0,y:0});const [collapsed,setCollapsed]=useState<string[]>([]);const drag=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);
 function linkTree(root:ImportedMindMapNode):ImportedMindMapNode{const name=root.title.replace(/^第[一二三四五六七八九十\d]+[章节]\s*/,"").trim();const section=sections.find(x=>[x.title,x.titleEn].some(title=>title.replace(/^第\s*\d+\s*节\s*/,"").trim()===name));const point=points.find(x=>x.title===name||x.titleEn===name);return{...root,linkedSectionId:section?.id,linkedKnowledgePointId:point?.id,children:root.children.map(linkTree)};}
 async function choose(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);setError("");try{const parsed=await parseMindMapFile(file);setPreview({sourceFileName:file.name,format:parsed.format,tree:linkTree(parsed.tree)});}catch(reason){setError(reason instanceof Error?reason.message:"PARSE_FAILED");}finally{setBusy(false);}}
 function confirm(){if(!preview)return;const now=new Date().toISOString();mutate(draft=>{const prior=draft.chapterMindMaps.find(x=>x.curriculumId===curriculumId&&x.chapterId===chapter.id);const value={sourceFileName:preview.sourceFileName,importedAt:now,format:preview.format,parsedTree:preview.tree,updatedAt:now};if(prior)Object.assign(prior,value);else draft.chapterMindMaps.push({...nowEntity(`chapter-mind-map-${curriculumId}-${chapter.id}`,draft.ownerId),curriculumId,chapterId:chapter.id,...value});});setPreview(undefined);setCollapsed([]);setScale(.9);setOffset({x:0,y:0});}
 function down(e:PointerEvent<HTMLDivElement>){if((e.target as HTMLElement).closest("a,button"))return;drag.current={x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y};e.currentTarget.setPointerCapture(e.pointerId);}function move(e:PointerEvent<HTMLDivElement>){if(drag.current)setOffset({x:drag.current.ox+e.clientX-drag.current.x,y:drag.current.oy+e.clientY-drag.current.y});}
 const tree=preview?.tree??saved?.parsedTree;
 return <section><input ref={input} className="sr-only" type="file" accept=".xmind,.md,.opml" onChange={choose}/>{!tree?<Card className="py-16 text-center"><h2 className="type-h2 text-primary">{en?"No mind map for this chapter":"本章暂无思维导图"}</h2><p className="type-small mt-3 text-secondary">{en?"Import an XMind, Markdown or OPML file. Preview it before saving.":"支持导入 XMind、Markdown 或 OPML 文件，保存前会先显示预览。"}</p><Button className="mt-6" onClick={()=>input.current?.click()} disabled={busy}>{busy?(en?"Parsing…":"正在解析…"):(en?"Import mind map":"导入思维导图")}</Button>{error?<p className="type-small mt-4 text-error" role="alert">{errorMessage(error,en)}</p>:null}</Card>:<><div className="flex flex-col gap-3 border-b border-border pb-4 tablet:flex-row tablet:items-center tablet:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="type-h3 text-primary">{preview?(en?"Import preview":"导入预览"):tree.title}</h2>{preview?<Badge variant="warm">{en?"Not saved":"尚未保存"}</Badge>:null}</div><p className="type-caption mt-1 text-muted">{preview?.sourceFileName??saved?.sourceFileName} · {(preview?.format??saved?.format)?.toUpperCase()} · {mindMapNodeCount(tree)} {en?"nodes":"个节点"}</p></div><div className="flex flex-wrap gap-2">{preview?<><Button size="sm" onClick={confirm}>{saved?(en?"Confirm replacement":"确认替换"):(en?"Confirm import":"确认导入")}</Button><Button size="sm" variant="secondary" onClick={()=>setPreview(undefined)}>{en?"Cancel":"取消"}</Button></>:<Button size="sm" variant="secondary" onClick={()=>input.current?.click()}>{en?"Replace / re-import":"替换 / 重新导入"}</Button>}<Button size="sm" variant="secondary" onClick={()=>setScale(v=>Math.min(1.8,v+.1))}>＋</Button><Button size="sm" variant="secondary" onClick={()=>setScale(v=>Math.max(.45,v-.1))}>−</Button><Button size="sm" variant="secondary" onClick={()=>{setScale(.82);setOffset({x:0,y:0});}}>{en?"Fit":"适应屏幕"}</Button><Button size="sm" variant="secondary" onClick={()=>void frame.current?.requestFullscreen()}>{en?"Full screen":"全屏"}</Button></div></div>{error?<p className="type-small mt-3 text-error" role="alert">{errorMessage(error,en)}</p>:null}<div ref={frame} className="mt-4 h-[38rem] cursor-grab overflow-hidden rounded-lg border border-border bg-surface-muted touch-none active:cursor-grabbing" onPointerDown={down} onPointerMove={move} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><div className="min-h-full min-w-max p-10 transition-transform" style={{transform:`translate(${offset.x}px, ${offset.y}px) scale(${scale})`,transformOrigin:"left top"}}><MindNode root={tree} depth={0} collapsed={collapsed} toggle={id=>setCollapsed(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}/></div></div></>}</section>;
}
function MindNode({root,depth,collapsed,toggle}:{root:ImportedMindMapNode;depth:number;collapsed:string[];toggle:(id:string)=>void}){const hidden=collapsed.includes(root.id);return <div className="flex items-start gap-7"><div className={`mt-2 w-56 shrink-0 rounded-lg border px-4 py-3 shadow-soft ${depth===0?"border-accent bg-accent-soft":"border-border-strong bg-surface-raised"}`}><p className="type-small font-medium text-primary">{root.title}</p>{root.children.length?<button type="button" className="mt-2 type-caption text-accent" onClick={()=>toggle(root.id)} aria-expanded={!hidden}>{hidden?"＋":"−"} {root.children.length}</button>:null}</div>{!hidden&&root.children.length?<div className="grid gap-3 border-l-2 border-border-strong pl-7">{root.children.map(child=><MindNode key={child.id} root={child} depth={depth+1} collapsed={collapsed} toggle={toggle}/>)}</div>:null}</div>;}
function errorMessage(code:string,en:boolean){const messages:Record<string,[string,string]>={UNSUPPORTED_FORMAT:["仅支持 .xmind、.md、.opml 文件。","Only .xmind, .md and .opml files are supported."],INVALID_OPML:["OPML 文件格式无效。","The OPML file is invalid."],INVALID_XMIND:["XMind 文件没有可读取的主题。","The XMind file has no readable topic."],UNSUPPORTED_XMIND_VERSION:["暂不支持此 XMind 文件版本，请导出为新版 .xmind 或 OPML。","This XMind version is not supported. Export a current .xmind or OPML file."],EMPTY_MIND_MAP:["文件中没有可读取的导图节点。","No readable nodes were found."]};return(messages[code]??["文件解析失败，请检查文件后重试。","The file could not be parsed."])[en?1:0];}
