"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Badge, Button, Card, Progress, Textarea } from "@/components/ui";
import { buildCurriculumCatalog, buildTeachingUnit, completeCurriculumSection, evaluateFeynman, recordQuickCheckAttempt, scheduleSectionKnowledgeReviews } from "@/domain";
import type { BetaQuestion } from "@/domain/beta";
import type { Locale } from "@/i18n/config";
import { useBetaData } from "@/providers";
import { BetaPage, nowEntity, uid } from "@/features/beta/shared";
import { addKnowledgeToRecitation } from "@/features/beta/recitation-service";
import { reviewDefaults } from "@/domain/review/review-engine";
import { ChapterMindMap } from "./chapter-mind-map";

const text = {
  "zh-CN": { objectives:"学完这一节，你能够", explain:"先用简单的话理解", formal:"正式定义", examples:"具体例子", contrast:"反例与辨析", exam:"考试时怎么识别", mistakes:"常见误区", summary:"最后总结", feynman:"用自己的话讲给我听", prompt:"不要看上面的内容。假设对方完全不了解这个概念，请用自己的话解释，并举一个例子。", skip:"暂时跳过", check:"检查复述", retry:"再试一次", matched:"已经讲到", missing:"还缺", quick:"即时检测", submit:"提交答案", next:"下一题", finish:"完成本节", recite:"加入背诵", review:"加入复习", back:"返回课程", prev:"上一节", nextLesson:"下一节", estimate:"预计", estimated:"掌握度为系统估计", correct:"回答正确", incorrect:"再看一次讲解", answer:"答案与解析", noQuestions:"本节没有独立题目，已使用同科目基础检测。", completed:"本节已完成", listen:"听读", speechUnavailable:"当前浏览器不支持语音输入，可继续文字复述。", speak:"语音输入", stop:"停止语音输入" },
  en: { objectives:"By the end of this lesson, you can", explain:"Start with a plain explanation", formal:"Formal definition", examples:"Concrete examples", contrast:"Counterexamples and distinctions", exam:"How to recognize it in an exam", mistakes:"Common mistakes", summary:"Summary", feynman:"Explain it in your own words", prompt:"Do not look above. Explain this idea to someone new to the topic, and give one example.", skip:"Skip for now", check:"Check explanation", retry:"Try again", matched:"Covered", missing:"Still missing", quick:"Quick check", submit:"Submit answer", next:"Next question", finish:"Complete lesson", recite:"Add to recitation", review:"Schedule review", back:"Back to course", prev:"Previous lesson", nextLesson:"Next lesson", estimate:"Estimated", estimated:"Mastery is a system estimate", correct:"Correct", incorrect:"Review the explanation", answer:"Answer and explanation", noQuestions:"This lesson uses a subject-level check because it has no dedicated question yet.", completed:"Lesson complete", listen:"Listen", speechUnavailable:"Speech input is unavailable in this browser. You can continue by typing.", speak:"Voice input", stop:"Stop voice input" },
};

export function LessonScreen({ locale, curriculumId, chapterId, sectionId }: { locale: Locale; curriculumId: string; chapterId: string; sectionId: string }) {
  const { state, mutate } = useBetaData(); const l = text[locale]; const catalog = useMemo(() => buildCurriculumCatalog(state), [state]);
  const curriculum = catalog.curricula.find((item) => item.id === curriculumId); const chapter = catalog.chapters.find((item) => item.id === chapterId && item.curriculumId === curriculumId); const section = catalog.sections.find((item) => item.id === sectionId && item.chapterId === chapterId); const unit = section ? buildTeachingUnit(state, section) : null;
  const [step, setStep] = useState(section?.kind === "chapter_review" ? 2 : 0); const [response, setResponse] = useState(""); const [feedback, setFeedback] = useState<ReturnType<typeof evaluateFeynman> | null>(null); const [listening, setListening] = useState(false);
  const sections = catalog.sections.filter((item) => item.chapterId === chapterId).sort((a,b)=>a.order-b.order);
  const courseChapters = catalog.chapters.filter((item) => item.curriculumId === curriculumId).sort((a,b)=>a.order-b.order);
  const courseSections = courseChapters.flatMap((courseChapter) => catalog.sections.filter((item) => item.chapterId === courseChapter.id).sort((a,b)=>a.order-b.order));
  const at = courseSections.findIndex((item) => item.id === sectionId); const previous = courseSections[at-1]; const next = courseSections[at+1];
  const existing = state.sectionProgress.find((item) => item.sectionId === sectionId); const progress = existing?.status === "completed" ? 100 : step <= 1 ? 25 : step === 2 ? 55 : step === 3 ? 75 : 88;
  const questions = useMemo(() => { if (!curriculum) return []; const ids = new Set(unit?.quickCheckQuestionIds ?? []); let list = state.questions.filter((item) => ids.has(item.id)); if (list.length < 2) list = [...list, ...state.questions.filter((item) => item.subjectId === curriculum.subjectId && !ids.has(item.id))]; return list.slice(0, 5); }, [curriculum, state.questions, unit]);

  useEffect(() => {
    if (!curriculum || !chapter || !section) return;
    mutate((draft) => { const now = new Date().toISOString(); let course = draft.courseProgress.find((item) => item.curriculumId === curriculum.id); if (!course) { course = { ...nowEntity(`course-progress-${curriculum.id}`, draft.ownerId), curriculumId: curriculum.id, startedAt: now, lastStudiedAt: now }; draft.courseProgress.push(course); } course.lastChapterId = chapter.id; course.lastSectionId = section.id; course.lastStudiedAt = now; const item = draft.sectionProgress.find((entry) => entry.sectionId === section.id); if (!item) draft.sectionProgress.push({ ...nowEntity(`section-progress-${section.id}`, draft.ownerId), curriculumId: curriculum.id, chapterId: chapter.id, sectionId: section.id, status: "learning", lessonViewed: true, feynmanStatus: "pending", quickCheckCompleted: false, quickCheckCorrect: 0, quickCheckTotal: 0, startedAt: now, lastStudiedAt: now }); else if (!item.lessonViewed) { item.lessonViewed = true; item.lastStudiedAt = now; } });
    // Opening a stable lesson is the intentional trigger; state changes must not restart the lesson.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [curriculumId, chapterId, sectionId]);
  if (!curriculum || !chapter || !section || !unit) return <BetaPage title={l.back} description=""><Card>{locale === "en" ? "Lesson not found." : "没有找到这一节课程。"}</Card></BetaPage>;
  const activeCurriculum = curriculum; const activeChapter = chapter; const activeSection = section; const activeUnit = unit;
  const sectionKnowledgePointIds = section.knowledgePointIds;
  const sectionPoints = sectionKnowledgePointIds.map((id)=>state.knowledgePoints.find((item)=>item.id===id)).filter(Boolean) as typeof state.knowledgePoints;
  const verifiedPastQuestions = state.questions.filter((item)=>item.isOfficial===true&&typeof item.year==="number"&&item.knowledgePointId&&sectionKnowledgePointIds.includes(item.knowledgePointId));
  const sourcePdfs = state.pdfDocuments.filter((item)=>item.subjectId===curriculum.subjectId&&(item.chapterId===chapter.sourceChapterId||item.ownerRecordId===chapter.sourceChapterId));
  const textbookCourse = curriculum.subjectId === "subject-psychology-312";

  function addLessonRecitation(draft: typeof state) {
    sectionKnowledgePointIds.forEach((id) => addKnowledgeToRecitation(draft, id));
    if (sectionKnowledgePointIds.length || draft.recitations.some((item) => item.id === `recitation-${activeSection.id}`)) return;
    draft.recitations.push({ ...nowEntity(`recitation-${activeSection.id}`, draft.ownerId), title: activeSection.title.replace(/^第\s*\d+\s*节\s*/, ""), category: activeChapter.title, content: activeUnit.summary, status: "today", favorite: false, nextReviewAt: new Date().toLocaleDateString("sv-SE"), subjectId: activeCurriculum.subjectId, chapterId: activeChapter.sourceChapterId, type: "custom", reviewCount: 0, mastery: "new" });
  }

  function saveFeynman(skipped = false) { const result = evaluateFeynman(response, unit!); setFeedback(result); mutate((draft) => { const now=new Date(); const prior = draft.feynmanAttempts.filter((item) => item.sectionId === sectionId); draft.feynmanAttempts.push({ ...nowEntity(uid("feynman"), draft.ownerId), sectionId, knowledgePointIds: sectionKnowledgePointIds, response: skipped ? "" : response, selfRating: skipped ? "again" : result.complete ? "good" : "hard", feedback: skipped ? "Skipped by learner" : result.message, retryCount: prior.length, matchedTerms: skipped ? [] : result.matchedTerms, missingTerms: skipped ? unit!.requiredTerms : result.missingTerms }); const item = draft.sectionProgress.find((entry) => entry.sectionId === sectionId); if (item) { item.feynmanStatus = skipped ? "skipped" : result.complete ? "completed" : "pending"; item.lastStudiedAt = now.toISOString(); } if(skipped||!result.complete)scheduleSectionKnowledgeReviews(draft,sectionKnowledgePointIds,now); }); if (skipped || result.complete) setStep(4); }
  function speechInput() { const SpeechRecognition = (window as unknown as { SpeechRecognition?: new()=>{lang:string;continuous:boolean;interimResults:boolean;onresult:(event:{results:ArrayLike<{0:{transcript:string}}>} )=>void;onend:()=>void;start:()=>void;stop:()=>void}; webkitSpeechRecognition?: new()=>{lang:string;continuous:boolean;interimResults:boolean;onresult:(event:{results:ArrayLike<{0:{transcript:string}}>} )=>void;onend:()=>void;start:()=>void;stop:()=>void} }).SpeechRecognition ?? (window as unknown as { webkitSpeechRecognition?: new()=>{lang:string;continuous:boolean;interimResults:boolean;onresult:(event:{results:ArrayLike<{0:{transcript:string}}>} )=>void;onend:()=>void;start:()=>void;stop:()=>void} }).webkitSpeechRecognition; if (!SpeechRecognition) { window.alert(l.speechUnavailable); return; } const recognition = new SpeechRecognition(); recognition.lang = locale === "en" ? "en-US" : "zh-CN"; recognition.continuous = false; recognition.interimResults = false; recognition.onresult = (event) => setResponse((value) => `${value}${value ? " " : ""}${event.results[0][0].transcript}`); recognition.onend = () => setListening(false); setListening(true); recognition.start(); }
  function scheduleReview() { mutate((draft) => { sectionKnowledgePointIds.forEach((id) => { const point = draft.knowledgePoints.find((item)=>item.id===id); if (point && !draft.reviewItems.some((item)=>item.kind==="knowledge"&&item.targetId===id&&item.status==="due")) draft.reviewItems.push({ ...nowEntity(uid("review"),draft.ownerId),kind:"knowledge",targetId:id,title:point.title,dueDate:new Date().toLocaleDateString("sv-SE"),status:"due",subjectId:point.subjectId,chapterId:point.chapterId,...reviewDefaults("knowledge") }); }); if (!sectionKnowledgePointIds.length) { addLessonRecitation(draft); const targetId=`recitation-${activeSection.id}`; if(!draft.reviewItems.some((item)=>item.kind==="recitation"&&item.targetId===targetId&&item.status==="due")) draft.reviewItems.push({ ...nowEntity(uid("review"),draft.ownerId),kind:"recitation",targetId,title:activeSection.title,dueDate:new Date().toLocaleDateString("sv-SE"),status:"due",subjectId:activeCurriculum.subjectId,chapterId:activeChapter.sourceChapterId,...reviewDefaults("recitation") }); } }); }
  return <BetaPage title={locale === "en" ? section.titleEn : section.title} description={`${locale === "en" ? chapter.titleEn : chapter.title} · ${l.estimate} ${section.estimatedMinutes} min`} action={<Link href={`/${locale}/learn/${curriculum.id}`} className="type-label text-accent hover:underline">← {l.back}</Link>}>
    <div className="reading-container grid gap-6"><nav aria-label={locale==="en"?"Lesson tools":"小节学习工具"} className="sticky top-0 z-20 -mx-2 flex gap-1 overflow-x-auto rounded-lg border border-border bg-surface-raised/95 p-2 shadow-soft"><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(2)}>{locale==="en"?(textbookCourse?"Textbook":"Learning content"):(textbookCourse?"教材内容":"学习内容")}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(2)}>{locale==="en"?"Knowledge":"本节知识点"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(2)}>{locale==="en"?"Exam points":"本节考点"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(2)}>{locale==="en"?"Past papers":"历年真题"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(4)}>{locale==="en"?"Practice":"本节刷题"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>mutate(addLessonRecitation)}>{locale==="en"?"Recitation":"背诵"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(3)}>{locale==="en"?"Feynman":"费曼模式"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(3)}>{locale==="en"?"Recall":"我要复述"}</button><button className="min-h-10 shrink-0 rounded-md px-3 type-label text-secondary hover:bg-surface-muted" onClick={()=>setStep(2)}>{locale==="en"?"Notes":"我的笔记"}</button></nav><div><div className="flex items-center justify-between gap-3"><Badge variant={existing?.status === "completed" ? "success" : "warm"}>{existing?.status === "completed" ? l.completed : `${String(section.order).padStart(2,"0")}/${String(sections.length).padStart(2,"0")}`}</Badge><span className="type-caption text-muted">{progress}% · {l.estimated}</span></div><Progress className="mt-3" value={progress}/></div>
      {step === 0 ? <Card variant="elevated" className="grid gap-6"><div><p className="type-caption text-muted">{locale === "en" ? "Today's lesson" : "今天我们学习"}</p><h2 className="type-h1 mt-2 text-primary">{locale === "en" ? section.titleEn.replace(/^\d+\.\d+\s*/,"") : section.title.replace(/^\d+\.\d+\s*/,"")}</h2><p className="type-body mt-4 text-secondary">{locale === "en" ? unit.hookEn : unit.hook}</p></div><div className="rounded-lg bg-warm-oat-soft p-5"><h3 className="type-label text-primary">{l.objectives}</h3><ol className="mt-3 grid gap-2 pl-5 type-small text-secondary">{unit.learningObjectives.map((item)=><li className="list-decimal" key={item}>{item}</li>)}</ol></div><Button onClick={()=>setStep(1)}>{locale === "en" ? "Start explanation" : "开始讲解"} →</Button></Card> : null}
      {step === 1 ? <LessonBlock title={l.explain} body={unit.simpleExplanation} action={<Button onClick={()=>setStep(2)}>{locale === "en" ? "See formal definition" : "查看正式定义"} →</Button>}/> : null}
      {step === 2 ? <Card variant="elevated" className="flow-root [&>section]:mt-7">
        <aside className="mb-7 rounded-md border border-border bg-surface-muted p-4 desktop:sticky desktop:top-20 desktop:float-right desktop:mb-5 desktop:ml-7 desktop:w-64"><h3 className="type-label text-primary">{locale==="en"?"Knowledge in this section":"本节知识点"}</h3><ul className="mt-3 grid gap-2 type-small text-secondary">{sectionPoints.length?sectionPoints.map((item)=><li key={item.id}><a href={`#knowledge-${item.id}`} className="hover:text-accent">• {locale==="en"?item.titleEn:item.title}</a></li>):unit.learningObjectives.map((item,index)=><li key={index}>• {item}</li>)}</ul><h3 className="type-label mt-5 text-primary">{locale==="en"?"Related exam points":"相关考点"}</h3><ul className="mt-3 grid gap-2 type-small text-secondary">{unit.examTips.slice(0,4).map((item,index)=><li key={index}>• {item}{verifiedPastQuestions.filter((question)=>question.knowledgePointId&&sectionKnowledgePointIds.includes(question.knowledgePointId)).map((question)=>question.year).filter(Boolean).slice(0,2).map((year)=><Badge key={year} variant="neutral" className="ml-1">{year}</Badge>)}</li>)}</ul><p className="type-caption mt-5 text-muted">{locale==="en"?`Progress ${progress}%`:`学习进度 ${progress}%`}</p></aside>
        <section className="rounded-md border border-border bg-surface-muted p-4"><div className="flex flex-wrap items-center gap-2"><h3 className="type-h3 text-primary">{locale==="en"?"Textbook basis":"教材内容"}</h3><Badge variant={section.sourceStatus==="verified"?"neutral":"warm"}>{section.sourceStatus==="verified"?(locale==="en"?"Outline verified":"目录已核验"):(locale==="en"?"Calibration pending":"待教材校准")}</Badge></div><p className="type-small mt-3 text-secondary">{sourcePdfs.length?(locale==="en"?`${sourcePdfs.length} personal textbook PDF(s) are linked to this chapter. Open the PDF library to read the source text.`:`本章已关联 ${sourcePdfs.length} 份个人教材 PDF；教材正文请以资料库文件为准。`):(locale==="en"?"No verifiable textbook text is linked. The teaching below is system-authored guidance and is not presented as textbook wording.":"尚未关联可核验的教材正文。下面内容是系统原创教学辅助，不冒充教材原文、页码或原题。")}</p><p className="type-caption mt-2 text-muted">{section.sourceNote}</p></section>
        <LessonPart title={locale==="en"?"Plain-language teaching":"通俗讲解"} items={[unit.simpleExplanation]}/><LessonPart title={l.formal} items={[unit.formalDefinition]}/><LessonPart title={l.examples} items={unit.examples}/>
        <section><h3 className="type-h3 text-primary">{locale==="en"?"Knowledge points":"本节知识点"}</h3><div className="mt-3 grid gap-5">{sectionPoints.map((item,index)=><article id={`knowledge-${item.id}`} key={item.id} className="scroll-mt-24 border-l-2 border-border-strong pl-5"><p className="type-caption text-muted">{index+1}. {locale==="en"?"Concept / definition":"概念 / 定义"}</p><h4 className="type-h3 mt-2 text-primary">{locale==="en"?item.titleEn:item.title}</h4><p className="mt-3 text-[1rem] leading-8 text-secondary">{item.definition??item.coreConcept}</p><p className="type-caption mt-5 text-muted">{locale==="en"?"Main content":"主要内容"}</p><p className="mt-2 text-[1rem] leading-8 text-secondary">{item.explanation??item.keyPoints}</p>{item.examples?.[0]?<div className="mt-4 rounded-md bg-warm-oat-soft p-4"><p className="type-label text-primary">{locale==="en"?"Teaching aid example":"教学辅助 · 例子"}</p><p className="type-small mt-2 text-secondary">{item.examples[0]}</p></div>:null}</article>)}</div></section><LessonPart title={locale==="en"?"Exam points":"本节考点"} items={unit.examTips}/><LessonPart title={l.contrast} items={[...unit.counterExamples,...unit.comparison]}/><LessonPart title={l.mistakes} items={unit.commonMistakes}/>
        <section><h3 className="type-h3 text-primary">{locale==="en"?"Verified past-paper questions":"历年真题"}</h3>{verifiedPastQuestions.length?<div className="mt-3 grid gap-3">{verifiedPastQuestions.map((item)=><div key={item.id} className="rounded-md border border-border p-4"><Badge variant="neutral">{item.year}</Badge><p className="type-body mt-2 text-secondary">{item.stem}</p></div>)}</div>:<p className="type-small mt-3 rounded-md bg-surface-muted p-4 text-secondary">{locale==="en"?"No verified past-paper question is linked to this section. System exercises are kept separate below.":"本节暂无已核验年份和来源的历年真题；不会用系统原创题冒充真题。"}</p>}</section>
        <LessonPart title={l.summary} items={[unit.summary]}/>{section.kind==="chapter_review"?<ChapterMindMap locale={locale} curriculumId={curriculum.id} chapter={chapter} sections={sections} points={state.knowledgePoints} questions={state.questions}/>:null}{sectionPoints[0]?<section><h3 className="type-h3 text-primary">{locale==="en"?"My notes":"我的笔记"}</h3><Textarea className="mt-3" rows={5} defaultValue={sectionPoints[0].personalNote} onBlur={(event)=>mutate((draft)=>{const point=draft.knowledgePoints.find((item)=>item.id===sectionPoints[0].id);if(point){point.personalNote=event.target.value;point.updatedAt=new Date().toISOString();}})} /></section>:null}
        {section.id==="curriculum-section-english-vocabulary"?<Link href={`/${locale}/english`} className="inline-flex min-h-11 items-center justify-center rounded-md border border-border-strong bg-surface px-4 type-label text-primary hover:bg-surface-muted">{locale==="en"?"Open one-word study":"打开逐词学习"} →</Link>:null}<Button onClick={()=>setStep(3)}>{l.feynman} →</Button></Card> : null}
      {step === 3 ? <Card variant="elevated"><Badge variant="apricot">Feynman</Badge><h2 className="type-h2 mt-4 text-primary">{l.feynman}</h2><p className="type-body mt-3 text-secondary">{locale === "en" ? l.prompt : unit.feynmanPrompts[0] ?? l.prompt}</p><Textarea className="mt-5" rows={7} value={response} onChange={(event)=>setResponse(event.target.value)} aria-label={l.feynman}/><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" onClick={speechInput}>{listening ? l.stop : l.speak}</Button><Button onClick={()=>saveFeynman(false)} disabled={response.trim().length < 8}>{l.check}</Button><Button variant="ghost" onClick={()=>saveFeynman(true)}>{l.skip}</Button></div>{feedback ? <div className={`mt-5 rounded-md border p-4 ${feedback.complete?"border-success bg-success-soft":"border-border bg-surface-muted"}`} aria-live="polite"><p className="type-label text-primary">{feedback.message}</p>{feedback.matchedTerms.length?<p className="type-small mt-2 text-secondary">✓ {l.matched}: {feedback.matchedTerms.join("、")}</p>:null}{feedback.missingTerms.length?<p className="type-small mt-1 text-secondary">○ {l.missing}: {feedback.missingTerms.join("、")}</p>:null}{!feedback.complete?<Button className="mt-3" size="sm" variant="secondary" onClick={()=>{setFeedback(null);setResponse("");}}>{l.retry}</Button>:null}</div>:null}</Card> : null}
      {step === 4 ? <QuickCheck locale={locale} questions={questions} curriculumId={curriculum.id} chapterId={chapter.id} chapterSectionIds={sections.map((item)=>item.id)} sectionId={section.id} knowledgePointIds={section.knowledgePointIds} onDone={()=>setStep(5)}/> : null}
      {step === 5 ? <Card variant="elevated" className="text-center"><Badge variant="success">✓ {l.completed}</Badge><h2 className="type-h2 mt-4 text-primary">{l.summary}</h2><p className="type-body mt-3 text-secondary">{unit.summary}</p><div className="mx-auto mt-5 max-w-2xl rounded-md bg-warm-oat-soft p-4 text-left"><p className="type-label text-primary">{locale === "en" ? "Required recall" : "本节必背"}</p><p className="type-small mt-2 text-secondary">{unit.summary}</p></div><div className="mt-6 flex flex-wrap justify-center gap-2"><Button variant="secondary" onClick={()=>mutate(addLessonRecitation)}>{l.recite}</Button><Button variant="secondary" onClick={scheduleReview}>{l.review}</Button>{next?<Link href={`/${locale}/learn/${curriculum.id}/${next.chapterId}/${next.id}`} className="inline-flex min-h-11 items-center rounded-md border border-accent bg-accent px-4 type-label text-white hover:bg-accent-hover">{l.nextLesson} →</Link>:<Link href={`/${locale}/learn/${curriculum.id}`} className="inline-flex min-h-11 items-center rounded-md border border-accent bg-accent px-4 type-label text-white">{l.back}</Link>}</div></Card> : null}
      <nav className="flex justify-between gap-4 border-t border-border pt-5" aria-label={locale === "en" ? "Lesson navigation" : "课程导航"}>{previous?<Link className="type-label text-accent" href={`/${locale}/learn/${curriculum.id}/${previous.chapterId}/${previous.id}`}>← {l.prev}</Link>:<span/>}{next?<Link className="type-label text-accent" href={`/${locale}/learn/${curriculum.id}/${next.chapterId}/${next.id}`}>{l.nextLesson} →</Link>:null}</nav>
    </div>
  </BetaPage>;
}

function LessonBlock({title,body,action}:{title:string;body:string;action:ReactNode}){return <Card variant="elevated"><p className="type-caption text-muted">{title}</p><p className="mt-4 text-lg leading-8 text-primary whitespace-pre-wrap">{body}</p><div className="mt-8">{action}</div></Card>}
function LessonPart({title,items}:{title:string;items:string[]}){return <section><h3 className="type-h3 text-primary">{title}</h3><div className="mt-3 grid gap-3">{items.filter(Boolean).map((item,index)=><p key={`${title}-${index}`} className="rounded-md bg-surface-muted p-4 type-body text-secondary">{item}</p>)}</div></section>}

function QuickCheck({locale,questions,curriculumId,chapterId,chapterSectionIds,sectionId,knowledgePointIds,onDone}:{locale:Locale;questions:BetaQuestion[];curriculumId:string;chapterId:string;chapterSectionIds:string[];sectionId:string;knowledgePointIds:string[];onDone:()=>void}){
  const {mutate}=useBetaData();const l=text[locale];const [index,setIndex]=useState(0);const [selected,setSelected]=useState<string[]>([]);const [submitted,setSubmitted]=useState(false);const [correctCount,setCorrectCount]=useState(0);const question=questions[index];const correct=question ? selected.length===question.answer.length&&[...selected].sort().every((item,at)=>item===[...question.answer].sort()[at]):false;
  function choose(id:string){if(!question||submitted)return;setSelected(question.questionType==="multiple"?(selected.includes(id)?selected.filter(item=>item!==id):[...selected,id]):[id]);}
  function submit(){if(!question||!selected.length)return;setSubmitted(true);if(correct)setCorrectCount(value=>value+1);mutate((draft)=>{recordQuickCheckAttempt(draft,question.id,selected,new Date(),uid);});}
  function finish(finalCorrect:number){mutate((draft)=>{const now=new Date();completeCurriculumSection(draft,{curriculumId,chapterId,chapterSectionIds,sectionId,correct:finalCorrect,total:questions.length},now);scheduleSectionKnowledgeReviews(draft,knowledgePointIds,now);knowledgePointIds.forEach(id=>{const point=draft.knowledgePoints.find(item=>item.id===id);if(point&&finalCorrect===questions.length)point.mastery="learning";});});onDone();}
  if(!question)return <Card><p className="type-body text-secondary">{l.noQuestions}</p><Button className="mt-4" onClick={()=>finish(0)}>{l.finish}</Button></Card>;
  const sourceLabel=question.isOfficial&&question.year?`${question.year} · ${question.sourceLabel??question.source}`:(locale==="en"?"System-authored practice":"系统原创练习题");
  return <Card variant="elevated"><div className="flex flex-wrap gap-2"><Badge variant="warm">{l.quick} · {index+1}/{questions.length}</Badge><Badge variant="neutral">{sourceLabel}</Badge></div><h2 className="type-h3 mt-4 text-primary">{question.stem}</h2><div className="mt-5 grid gap-3">{question.options.map((option,optionIndex)=><button key={option.id} type="button" onClick={()=>choose(option.id)} aria-pressed={selected.includes(option.id)} className={`min-h-12 rounded-md border p-3 text-left type-body ${selected.includes(option.id)?"border-accent bg-accent-soft":"border-border bg-surface hover:border-border-strong"}`}>{String.fromCharCode(65+optionIndex)}. {option.text}</button>)}</div>{submitted?<div className={`mt-5 rounded-md border p-4 ${correct?"border-success bg-success-soft":"border-error bg-error-soft"}`} aria-live="polite"><p className="type-label text-primary">{correct?l.correct:l.incorrect}</p><p className="type-small mt-2 text-secondary">{l.answer}: {question.answer.map(id=>question.options.find(option=>option.id===id)?.text).join("、")} · {question.explanation}</p></div>:null}<div className="mt-5 flex gap-2">{!submitted?<Button onClick={submit} disabled={!selected.length}>{l.submit}</Button>:index<questions.length-1?<Button onClick={()=>{setIndex(value=>value+1);setSelected([]);setSubmitted(false);}}>{l.next}</Button>:<Button onClick={()=>finish(correctCount+(correct?1:0))}>{l.finish}</Button>}</div></Card>;
}
