"use client";

import Link from "next/link";
import { useState } from "react";
import { Badge, Card, Progress } from "@/components/ui";
import { buildCurriculumCatalog, resolveContinueLearning } from "@/domain";
import type { Locale } from "@/i18n/config";
import { useBetaData } from "@/providers";
import { BetaPage } from "@/features/beta/shared";

const isPsychology = (id: string) => id.startsWith("curriculum-psych-");
const todayKey = () => new Date().toLocaleDateString("sv-SE");
const bookTones = ["bg-accent-soft", "bg-warm-oat-soft", "bg-dusty-rose-soft", "bg-surface-muted"];

export function PsychologyOverviewV4({ locale }: { locale: Locale }) {
  const { state } = useBetaData();
  const [query, setQuery] = useState("");
  const catalog = buildCurriculumCatalog(state);
  const books = catalog.curricula.filter((item) => item.subjectId === "subject-psychology-312");
  const sectionIds = new Set(catalog.sections.filter((section) => catalog.chapters.some((chapter) => books.some((book) => book.id === chapter.curriculumId) && chapter.id === section.chapterId)).map((item) => item.id));
  const today = todayKey();
  const learnedToday = state.sectionProgress.filter((item) => sectionIds.has(item.sectionId) && item.lastStudiedAt?.slice(0, 10) === today).length;
  const due = state.reviewItems.filter((item) => item.subjectId === "subject-psychology-312" && item.status === "due" && item.dueDate <= today).length;
  const questionIds = new Set(state.questions.filter((item) => item.subjectId === "subject-psychology-312").map((item) => item.id));
  const wrong = state.wrongQuestions.filter((item) => questionIds.has(item.questionId) && !item.mastered).length;
  const mastered = state.sectionProgress.filter((item) => sectionIds.has(item.sectionId) && item.status === "completed").length;
  const totalToday = state.tasks.filter((item) => item.subjectId === "subject-psychology-312" && item.date === today).length;
  const stats = locale === "en" ? [["Study today", `${learnedToday}/${totalToday} lessons`], ["Due review", `${due}`], ["Mistakes", `${wrong}`], ["Mastered", `${mastered}`]] : [["今日学习", `${learnedToday}/${totalToday} 节`], ["待复习", `${due} 个`], ["错题", `${wrong} 题`], ["已掌握", `${mastered} 个`]];
  const visibleBooks = books.filter((book) => `${book.title}${book.author}${book.edition}`.toLowerCase().includes(query.trim().toLowerCase()));

  return <BetaPage title={locale === "en" ? "312 Psychology" : "312 心理学"} description={locale === "en" ? "Seven core textbooks · systematic learning · past papers · focused preparation" : "七本主教材 · 系统化学习 · 真题结合 · 高效备考"} action={<label className="relative block w-full tablet:w-72"><span className="sr-only">{locale === "en" ? "Search" : "搜索知识点、章节、真题"}</span><span className="pointer-events-none absolute left-3 top-3 text-muted">⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} className="min-h-11 w-full rounded-md border border-border bg-surface-raised pl-9 pr-3 type-small text-primary shadow-soft outline-none focus:border-accent" placeholder={locale === "en" ? "Knowledge, chapters, past papers..." : "搜索知识点、章节、真题……"}/></label>}>
    <div className="grid grid-cols-2 gap-3 tablet:grid-cols-4">{stats.map(([label,value])=><Card key={label} padding="sm" className="min-h-24"><p className="type-small text-secondary">{label}</p><p className="type-h2 mt-3 text-primary">{value}</p></Card>)}</div>
    <section><h2 className="type-h2 text-primary">{locale === "en" ? "Core textbooks" : "七本教材"}</h2><div className="mt-4 grid gap-3 tablet:grid-cols-2 desktop:grid-cols-4">{visibleBooks.map((book,index)=>{
      const chapters=catalog.chapters.filter((item)=>item.curriculumId===book.id); const sections=catalog.sections.filter((item)=>chapters.some((chapter)=>chapter.id===item.chapterId));
      const completed=state.sectionProgress.filter((item)=>sections.some((section)=>section.id===item.sectionId)&&item.status==="completed").length; const percent=sections.length?Math.round(completed/sections.length*100):0;
      const progress=state.courseProgress.find((item)=>item.curriculumId===book.id); const next=sections.find((section)=>section.kind!=="chapter_review"&&!state.sectionProgress.some((item)=>item.sectionId===section.id&&item.status==="completed"))??sections[0];
      return <Card key={book.id} padding="sm" className="flex min-h-56 flex-col"><div className="flex gap-3"><div className={`flex h-20 w-14 shrink-0 items-center justify-center rounded-sm border border-border px-2 text-center type-caption font-semibold text-primary ${bookTones[index%bookTones.length]}`}>{book.title.replace(/[《》]/g,"").replace(/第.版|\d{4}版/g,"")}</div><div className="min-w-0"><h3 className="type-label leading-6 text-primary">{locale==="en"?book.titleEn:book.title}</h3><p className="type-caption mt-1 text-muted">{[book.author,book.edition].filter(Boolean).join(" · ")}</p>{book.status==="needs_pdf_calibration"?<Badge className="mt-2" variant="warm">{locale==="en"?"Calibration pending":"待教材校准"}</Badge>:null}</div></div><div className="mt-auto pt-4"><div className="flex items-center justify-between type-caption text-muted"><span>{locale==="en"?`${chapters.length} chapters`:`共 ${chapters.length} 章`}</span><span>{percent}%</span></div><Progress className="mt-2" value={percent}/><Link href={`/${locale}/learn/${book.id}${next?`#${next.id}`:""}`} className="mt-3 inline-flex min-h-10 w-full items-center justify-center rounded-md border border-accent bg-accent px-3 type-label text-white hover:bg-accent-hover">{progress?(locale==="en"?"Continue learning":"继续学习"):(locale==="en"?"Start learning":"开始学习")}</Link></div></Card>;
    })}</div></section>
  </BetaPage>;
}

export function SubjectCurriculumOverview({ locale, subjectId, title, description }: { locale: Locale; subjectId: string; title: string; description: string }) {
  const {state}=useBetaData(); const catalog=buildCurriculumCatalog(state); const courses=catalog.curricula.filter((item)=>item.subjectId===subjectId); const today=todayKey();
  const minutes=state.studySessions.filter((item)=>item.subjectId===subjectId&&item.startedAt.slice(0,10)===today).reduce((sum,item)=>sum+item.durationMinutes,0); const due=state.reviewItems.filter((item)=>item.subjectId===subjectId&&item.status==="due"&&item.dueDate<=today).length;
  const questionIds=new Set(state.questions.filter((item)=>item.subjectId===subjectId).map((item)=>item.id)); const wrong=state.wrongQuestions.filter((item)=>questionIds.has(item.questionId)&&!item.mastered).length; const mastered=state.knowledgePoints.filter((item)=>item.subjectId===subjectId&&item.mastery==="mastered").length;
  const stats=locale==="en"?[["Study today",`${minutes} min`],["Due review",String(due)],["Mistakes",String(wrong)],["Mastered",String(mastered)]]:[["今日学习",`${minutes} 分钟`],["待复习",String(due)],["错题",String(wrong)],["已掌握",String(mastered)]];
  return <BetaPage title={title} description={description}><div className="grid grid-cols-2 gap-3 tablet:grid-cols-4">{stats.map(([label,value])=><Card key={label} padding="sm"><p className="type-caption text-muted">{label}</p><p className="type-h2 mt-2 text-primary">{value}</p></Card>)}</div><div className="grid gap-4 tablet:grid-cols-2 desktop:grid-cols-3">{courses.map((course)=>{const chapters=catalog.chapters.filter((item)=>item.curriculumId===course.id);const sections=catalog.sections.filter((item)=>chapters.some((chapter)=>chapter.id===item.chapterId));const completed=sections.filter((section)=>state.sectionProgress.some((item)=>item.sectionId===section.id&&item.status==="completed")).length;const percent=sections.length?Math.round(completed/sections.length*100):0;const progress=state.courseProgress.find((item)=>item.curriculumId===course.id);return <Card key={course.id}><h2 className="type-h2 text-primary">{locale==="en"?course.titleEn:course.title}</h2><p className="type-small mt-2 text-secondary">{locale==="en"?course.descriptionEn:course.description}</p><div className="mt-5 flex justify-between type-caption text-muted"><span>{chapters.length} {locale==="en"?"chapters":"章"}</span><span>{percent}%</span></div><Progress className="mt-2" value={percent}/><Link href={`/${locale}/learn/${course.id}`} className="mt-5 inline-flex min-h-11 items-center justify-center rounded-md border border-accent bg-accent px-4 type-label text-white hover:bg-accent-hover">{progress?(locale==="en"?"Continue learning":"继续学习"):(locale==="en"?"Start learning":"开始学习")} →</Link></Card>})}</div></BetaPage>;
}

export function CourseWorkspace({ locale, curriculumId }: { locale: Locale; curriculumId: string }) {
  const { state } = useBetaData(); const catalog=buildCurriculumCatalog(state); const course=catalog.curricula.find((item)=>item.id===curriculumId);
  if(!course)return <BetaPage title={locale==="en"?"Learning Center":"学习中心"} description=""><Card>{locale==="en"?"Course not found.":"没有找到这门课程。"}</Card></BetaPage>;
  const chapters=catalog.chapters.filter((item)=>item.curriculumId===course.id).sort((a,b)=>a.order-b.order); const continued=resolveContinueLearning(state,{...catalog,curricula:[course]}); const activeChapter=continued?.chapter??chapters[0];
  const sections=catalog.sections.filter((item)=>item.chapterId===activeChapter?.id).sort((a,b)=>a.order-b.order); const activeSection=(continued?.section&&continued.section.chapterId===activeChapter?.id?continued.section:null)??sections.find((item)=>item.kind!=="chapter_review")??sections[0];
  const allSections=chapters.flatMap((chapter)=>catalog.sections.filter((item)=>item.chapterId===chapter.id)); const doneTotal=allSections.filter((section)=>state.sectionProgress.some((item)=>item.sectionId===section.id&&item.status==="completed")).length; const totalPercent=allSections.length?Math.round(doneTotal/allSections.length*100):0;
  const activeDone=sections.filter((section)=>state.sectionProgress.some((item)=>item.sectionId===section.id&&item.status==="completed")).length; const chapterPercent=sections.length?Math.round(activeDone/sections.length*100):0;
  const backHref=isPsychology(course.id)?`/${locale}/psychology`:course.subjectId==="subject-politics"?`/${locale}/politics`:course.subjectId==="subject-english"?`/${locale}/english`:`/${locale}/learn`;
  const points=activeSection?.knowledgePointIds.map((id)=>state.knowledgePoints.find((item)=>item.id===id)).filter(Boolean)??[]; const official=state.questions.filter((item)=>item.isOfficial&&item.year&&item.knowledgePointId&&activeSection?.knowledgePointIds.includes(item.knowledgePointId)); const lessonHref=`/${locale}/learn/${course.id}/${activeChapter?.id}/${activeSection?.id}`;
  const tools=[["📘",locale==="en"?"Textbook study":"教材学习",locale==="en"?"Learn this section's verified content":"学习本节已核验内容",lessonHref],["✏️",locale==="en"?"Section exercises":"本节刷题",locale==="en"?"Practice linked to this section":"练习本节关联题目",`${lessonHref}/practice`],["📄",locale==="en"?"Past papers":"历年真题",official.length?`${official.length} · ${official.map((item)=>item.year).join(" ")}`:(locale==="en"?"No verified papers":"暂无核验真题"),`${lessonHref}/past-papers`],["📕",locale==="en"?"Section recall":"本节背诵",locale==="en"?"Active recall with spaced review":"主动回忆并进入复习计划",`${lessonHref}/recitation`]];
  return <main className="page-container overflow-hidden"><div className="grid min-h-[calc(100dvh-9rem)] gap-5 desktop:grid-cols-[20rem_minmax(0,1fr)]">
    <aside className="rounded-lg border border-border bg-surface-raised desktop:sticky desktop:top-5 desktop:max-h-[calc(100dvh-7rem)]"><div className="border-b border-border p-5"><Link href={backHref} className="type-caption text-accent">← {locale==="en"?"Course center":"课程中心"}</Link><h1 className="type-h3 mt-3 text-primary">{locale==="en"?course.titleEn:course.title}</h1><p className="type-caption mt-1 text-muted">{[course.author,course.edition].filter(Boolean).join(" · ")}</p><div className="mt-4 flex justify-between type-caption text-muted"><span>{locale==="en"?"Total progress":"总进度"}</span><span>{totalPercent}%</span></div><Progress className="mt-2" value={totalPercent}/></div><div className="max-h-[calc(100dvh-18rem)] overflow-y-auto p-3">{chapters.map((chapter)=>{const chapterSections=catalog.sections.filter((item)=>item.chapterId===chapter.id).sort((a,b)=>a.order-b.order);const completed=chapterSections.filter((section)=>state.sectionProgress.some((item)=>item.sectionId===section.id&&item.status==="completed")).length;const percent=chapterSections.length?Math.round(completed/chapterSections.length*100):0;const current=chapter.id===activeChapter?.id;return <details key={chapter.id} open={current} className="border-b border-border py-1"><summary className={`flex cursor-pointer items-center justify-between gap-2 rounded-md px-2 py-3 type-small ${current?"bg-accent-soft text-primary":"text-secondary hover:bg-surface-muted"}`}><span className="font-medium">{locale==="en"?chapter.titleEn:chapter.title}</span><span className="shrink-0 type-caption text-muted">{percent}%</span></summary><div className="grid gap-0.5 pb-2 pl-3">{chapterSections.map((section)=>{const done=state.sectionProgress.some((item)=>item.sectionId===section.id&&item.status==="completed");const selected=section.id===activeSection?.id;return <Link key={section.id} href={`/${locale}/learn/${course.id}/${chapter.id}/${section.id}`} className={`flex min-h-10 items-center gap-2 rounded-md px-2 type-caption ${selected?"bg-accent-soft font-medium text-primary":"text-secondary hover:bg-surface-muted"}`}><span className={done?"text-success":"text-muted"}>{done?"●":"○"}</span><span className="min-w-0 flex-1">{locale==="en"?section.titleEn:section.title}</span>{section.kind==="chapter_review"?<span>⌘</span>:null}</Link>})}</div></details>})}</div></aside>
    <section className="min-w-0 py-1"><p className="type-caption text-muted">{locale==="en"?activeChapter?.titleEn:activeChapter?.title}</p><h2 className="type-h1 mt-2 text-primary">{locale==="en"?activeSection?.titleEn:activeSection?.title}</h2><div className="mt-4 flex flex-col gap-4 border-b border-border pb-5 tablet:flex-row tablet:items-end tablet:justify-between"><div className="w-full max-w-md"><div className="flex justify-between type-caption text-muted"><span>{locale==="en"?"Learning progress":"学习进度"}</span><span>{chapterPercent}%</span></div><Progress className="mt-2" value={chapterPercent}/></div><div className="flex gap-2"><Link href={lessonHref} className="inline-flex min-h-11 items-center justify-center rounded-md border border-accent bg-accent px-4 type-label text-white hover:bg-accent-hover">{locale==="en"?"Continue learning":"继续学习"}</Link><Link href={`${lessonHref}/practice`} className="inline-flex min-h-11 items-center justify-center rounded-md border border-border-strong bg-surface px-4 type-label text-primary hover:bg-surface-muted">{locale==="en"?"Practice":"做本节题"}</Link></div></div>
      <div className="mt-5 grid gap-4 tablet:grid-cols-[minmax(0,1.15fr)_minmax(16rem,.85fr)]"><Card><h3 className="type-h3 text-primary">{locale==="en"?"Section content":"本节学习内容"}</h3><div className="mt-4 grid gap-1">{points.map((point,index)=>{const done=state.sectionProgress.some((item)=>item.sectionId===activeSection?.id&&item.status==="completed");return <Link key={point!.id} href={`${lessonHref}#knowledge-${point!.id}`} className={`flex min-h-12 items-center gap-3 rounded-md px-3 type-small hover:bg-surface-muted ${index===0?"bg-accent-soft text-primary":"text-secondary"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full border ${index===0?"border-accent bg-accent text-white":"border-border-strong"}`}>{done?"✓":index+1}</span><span>{locale==="en"?point!.titleEn:point!.title}</span></Link>})}</div></Card><Card><h3 className="type-h3 text-primary">{locale==="en"?"Section tools":"本节工具"}</h3><div className="mt-3 divide-y divide-border">{tools.map(([icon,title,description,href])=><Link key={title} href={href} className="flex gap-3 py-3 hover:text-accent"><span className="text-lg">{icon}</span><span><span className="block type-label text-primary">{title}</span><span className="mt-0.5 block type-caption text-muted">{description}</span></span></Link>)}</div></Card></div>
    </section>
  </div></main>;
}

export const PsychologyCourseWorkspace = CourseWorkspace;
